К полю "доход_расход" нужно подтянуть "вид_дохода_расхода" из Справочника "Меппинг_опу". По значениям вид_дохода_расхода создавать доп столбцы из значений Субконто.

Смотрим 91.01:

1. Переоценка ГП - доп столбцов выделять не нужно.
2. Премии покупателям - для 91.01 это скорее премии от поставщиков за выполнение планового объема закупок, доп столбцы не нужны (КА уже есть), но нужно определять вид связи и сегмент.
3. Аренда - доп столбцов выделять не нужно.
4. Изменение ППА - добавить доп признак (столбец "объект для изм ппа") для Изменения ППА - столбец с ППА, чтобы найти по нему КА из Справочника (лист "ППА")
5. Финансовый доход - доп столбцов выделять не нужно.
6. Продажа активов - вид_доход_расход "Продажа прочего имущества" и "Продажа основных средств" подтянуть КА для 91.02 из 91.01 по номеру операции. Выручку свернуть с НДС (68.08 91.02), распределить расходы 9102, по которым не нашелся Документ из 9101
7. Кредитное обслуживание. Вытащить из субконто 97 счета РБП, это рбп по кредитным линиям. По этим РБП достать из справочника "КредитОбслуж" КА -> Сегмент КА -> Вид связи
8. Расходы по процентам. Для процентов, для которых нет КА (РБП аренда и лизинг 97 счет), подтянуть КА из справочника "ППА". Затем КА -> Сегмент КА -> Вид связи

In [10]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:,.2f}'.format
# CONTRACTOR_ACCOUNTS = ('58', '60', '62', '63', '66', '67', '75', '76')
CONTRACTOR_ACCOUNTS = ('03', '03.02', '03.03', '03.04', '19.01', '19.02', '19.03', '19.04', '19.05', '19.07', '19.08', '19.09', '57.11', '57.22', '58', '58.01', '58.01.1', '58.01.2', '58.02', '58.03', '58.03.1', '58.03.2', '58.03.3', '58.04', '58.05', '59', '59.01', '59.02', '59.03', '59.03.1', '59.03.2', '59.03.3', '60', '60.01', '60.02', '60.03', '60.21', '60.22', '60.31', '60.32', '62', '62.01', '62.02', '62.03', '62.21', '62.22', '62.31', '62.32', '63', '66', '66.01', '66.02', '66.03', '66.04', '66.21', '66.22', '66.23', '66.24', '67', '67.01', '67.02', '67.03', '67.04', '67.21', '67.22', '67.23', '67.24', '68.22', '68.22.1', '68.22.2', '68.32', '75', '75.01', '75.02', '76', '76.01.1', '76.01.2', '76.01.9', '76.02', '76.03', '76.05', '76.05.1', '76.05.2', '76.05.3', '76.05.4', '76.05.5', '76.05.6', '76.05.7', '76.05.8', '76.06', '76.07', '76.07.1', '76.07.2', '76.07.5', '76.07.9', '76.09', '76.10', '76.11', '76.18', '76.21', '76.22', '76.25', '76.26', '76.27', '76.27.1', '76.27.2', '76.27.5', '76.29', '76.32', '76.35', '76.36', '76.37', '76.37.1', '76.37.2', '76.37.5', '76.37.9', '76.39', '76.41', '76.АВ', '76.ВА', '76.К', '76.Н', '76.НА', '76.ОТ', '79.03', '80', '80.01', '80.02', '80.09', '81', '81.01', '81.02', '81.09', '94.02', '000', '001', '002', '003', '003.01', '003.02', '04', '004.01', '004.02', '005', '007', '008', '009', '011', '014.02', 'ВАЛ', 'ВАЛ.60', 'ВАЛ.62')
PPA_ACCOUNTS = ('01.09', '02.01', '01.01')
NDS_ACCOUNTS = ('68.02')
INTEREST_EXPENSES = ['Комиссия по факторингу', 'Расходы по процентам аренда', 'Расходы по процентам кредиты займы', 'Расходы по процентам лизинг', 'Расходы по процентам прочие']
name_company = "РЗК"

In [3]:
'76.15' in CONTRACTOR_ACCOUNTS

False

In [4]:
# вспомогательные функции
def calculate_connection_type(df_result: pd.DataFrame) -> pd.Series:
        """Рассчитывает вид_связи на основе группа_ка и сегмент_ка."""
        conditions = [
            df_result['группа_ка'] == '3 лица',
            df_result['группа_ка'] == 'Прочие ГАП',
            (df_result['группа_ка'] == 'ГСК') & (df_result['сегмент_ка'] == df_result['сегмент']),
            (df_result['группа_ка'] == 'ГСК') & (df_result['сегмент_ка'] != df_result['сегмент']),
        ]
        choices = [
            '3 лица',
            'Прочие ГАП',
            'ГСК внутрисегмент.',
            'ГСК межсегмент.',
        ]
        # ★ STRING вместо category
        result = np.select(conditions, choices, default='не_указано')
        return pd.Series(result, index=df_result.index, dtype='string')

def clean_spaces_in_df(df: pd.DataFrame) -> pd.DataFrame:
    """
    Удаляет лишние пробелы в строковых столбцах DataFrame:
    - в начале и в конце строки
    - множественные пробелы между словами заменяет на один
    """
    # Создаем копию, чтобы не менять исходный датафрейм (защита от side-effects)
    df_clean = df.copy()
    
    # Находим все столбцы, которые могут содержать строки (object или string)
    str_cols = df_clean.select_dtypes(include=['object', 'string']).columns
    
    for col in str_cols:
        # split() разбивает по любым пробелам и убирает пустые строки
        # join(' ') собирает слова через один пробел
        # Это автоматически работает и с NaN (оставляет их как NaN)
        df_clean[col] = df_clean[col].str.split().str.join(' ')
        
    return df_clean

In [12]:
# загрузка сводного отчета по проводкам (все счета для ОПУ)
intermediate_data_df = pd.read_parquet('intermediate_data.parquet')

In [6]:
# Справочник Меппинг ОПУ
reference_df = pd.read_excel('C:/Users/a.karabedyan/Documents/PythonProject/decryption_collector_refactored_open_code/_REFERENCE_DATA/Справочники.xlsx', sheet_name='Меппинг_опу', dtype='string')
reference_df = clean_spaces_in_df(reference_df)

# Справочник ППА
reference_ppa_df = pd.read_excel('C:/Users/a.karabedyan/Documents/PythonProject/decryption_collector_refactored_open_code/_REFERENCE_DATA/Справочники.xlsx', sheet_name='ППА', dtype='string')
reference_ppa_df = clean_spaces_in_df(reference_ppa_df)

# Справочник Вид связи КА
group_companies_df = pd.read_excel('C:/Users/a.karabedyan/Documents/PythonProject/decryption_collector_refactored_open_code/_REFERENCE_DATA/Справочники.xlsx', sheet_name='ВидСвязиКА', dtype='string')
group_companies_df = clean_spaces_in_df(group_companies_df)

# Справочник компаний
companies_df = pd.read_excel('C:/Users/a.karabedyan/Documents/PythonProject/decryption_collector_refactored_open_code/_REFERENCE_DATA/Справочники.xlsx', sheet_name='КомпанииГруппы')
companies_df = clean_spaces_in_df(companies_df)

# Справочник рбп с кредитными лингиями
reference_rbp_credit = pd.read_excel('C:/Users/a.karabedyan/Documents/PythonProject/decryption_collector_refactored_open_code/_REFERENCE_DATA/Справочники.xlsx', sheet_name='КредитОбслуж')
reference_rbp_credit = clean_spaces_in_df(reference_rbp_credit)

In [7]:
# Выгружаем обороты по 91 и разделяем на субсчета
df_91_all = intermediate_data_df.loc[intermediate_data_df['Имя_файла'].str.contains('_91.0', na=False)]
df_9101 = df_91_all.loc[df_91_all['Кт'].str.startswith('91.01')]
df_9102 = df_91_all.loc[df_91_all['Дт'].str.startswith('91.02')]

In [8]:
# Общая обработка и 91.01, и 91.02

# переименуем столбцы, чтобы соотвествовать пр дальнейшем объединении таблиц,
# вынесем контрагентов в отдельный столбец

# 91.01
df_9101 = df_9101.rename(columns={'Субконто Кт_1': 'доход_расход', 'Сумма': 'оборот, тыс.ед.', 'Дт': 'Корр.счет', 'Кт': 'счет'})
mask = df_9101['Корр.счет'].astype(str).isin(CONTRACTOR_ACCOUNTS)
df_9101['контрагент'] = df_9101['Субконто Дт_1'].where(mask, 'не_указано').astype('string')
df_9101['оборот, тыс.ед.'] = df_9101.loc[:, 'оборот, тыс.ед.'] / -1000

#91.02
df_9102 = df_9102.rename(columns={'Субконто Дт_1': 'доход_расход', 'Сумма': 'оборот, тыс.ед.', 'Кт': 'Корр.счет', 'Дт': 'счет'})
mask = df_9102['Корр.счет'].astype(str).isin(CONTRACTOR_ACCOUNTS)
df_9102['контрагент'] = df_9102['Субконто Кт_1'].where(mask, 'не_указано').astype('string')
df_9102['оборот, тыс.ед.'] = df_9102.loc[:, 'оборот, тыс.ед.'] / 1000

df_9102.loc[df_9102['контрагент']!='не_указано'].to_excel('df_9102_KA.xlsx')

# Подтянем вид дохода/расхода по доходу/расходу из справочника

# Создаём составной ключ в справочнике и в данных
reference_df['_key'] = reference_df['счет'].astype(str) + '_' + reference_df['доход_расход'].astype(str)

df_9101['_key'] = df_9101['счет'].astype(str).str[:5] + '_' + df_9101['доход_расход'].astype(str)
df_9102['_key'] = df_9102['счет'].astype(str).str[:5] + '_' + df_9102['доход_расход'].astype(str)

# Маппинг
mapping = reference_df.drop_duplicates(subset='_key').set_index('_key')['вид_дохода_расхода']
df_9101['вид_дохода_расхода'] = df_9101['_key'].map(mapping).astype('string')
df_9102['вид_дохода_расхода'] = df_9102['_key'].map(mapping).astype('string')

# Убираем временный ключ
df_9101.drop(columns='_key', inplace=True)
df_9102.drop(columns='_key', inplace=True)
reference_df.drop(columns='_key', inplace=True)

# Заполняем отсутствующие значения
df_9101['вид_дохода_расхода'] = df_9101['вид_дохода_расхода'].fillna("не_указано")
df_9101 = df_9101.dropna(axis='columns', how='all')

df_9102['вид_дохода_расхода'] = df_9102['вид_дохода_расхода'].fillna("не_указано")
df_9102 = df_9102.dropna(axis='columns', how='all')

In [9]:
# тут нужно генерить ошибку с сообщением об отсутствующих значениях в справочнике, формировать файл с этими значениями, останавливать скрипт
if not df_9102.loc[df_9102['вид_дохода_расхода']=='не_указано'].empty:
    print('есть неучтенные расходы!')
if not df_9101.loc[df_9101['вид_дохода_расхода']=='не_указано'].empty:
    print('есть неучтенные доходы!')

In [10]:
# 91.01 обработка отдельно

# -------------------Добавим доп признак (столбец "объект для изм ппа") для Изменения ППА - столбец с ППА,
# чтобы найти по нему КА из Справочника (лист "ППА") -----------------

mask_ppa = df_9101['Корр.счет'].astype(str).str.startswith(PPA_ACCOUNTS, na=False)
df_9101['объект для изм ппа'] = df_9101['Субконто Дт_1'].where(mask_ppa, 'не_указано').astype('string')

# Маска по типу дохода (единое условие для обоих случаев)
mask_income = df_9101['вид_дохода_расхода'] == "Доходы от выбытия прав пользования активами, изменения условий договоров аренды"

# Маски по корр.счету
mask_01_09 = df_9101['Корр.счет'].str.startswith("01.09", na=False)
mask_02_01_or_01_01 = df_9101['Корр.счет'].str.startswith(("02.01", "01.01"), na=False)

# Маппинги из справочника ППА (с защитой от дубликатов)
mapping_ppa = (
    reference_ppa_df
    .drop_duplicates(subset='ос_ппа')
    .set_index('ос_ппа')['контрагент']
)
mapping_transfer = (
    reference_ppa_df
    .drop_duplicates(subset='ос_после_перехода_в_собственность')
    .set_index('ос_после_перехода_в_собственность')['контрагент']
)

# Условие 1: 01.09 → поиск по "ос_ппа"
mask_1 = mask_income & mask_01_09
mapped_1 = df_9101['объект для изм ппа'].map(mapping_ppa)

count_1 = (mask_1 & mapped_1.notna()).sum()
df_9101['контрагент'] = np.where(
    mask_1 & mapped_1.notna(),   # заменить только там, где условие И найдено значение
    mapped_1,                     # новое значение
    df_9101['контрагент']         # иначе — оставить текущее
)

# Условие 2: 02.01 или 01.01 → поиск по "ос_после_перехода_в_собственность"
mask_2 = mask_income & mask_02_01_or_01_01
mapped_2 = df_9101['объект для изм ппа'].map(mapping_transfer)

count_2 = (mask_2 & mapped_2.notna()).sum()
df_9101['контрагент'] = np.where(
    mask_2 & mapped_2.notna(),
    mapped_2,
    df_9101['контрагент']
)

# Явное приведение к string (np.where часто возвращает object)
df_9101['контрагент'] = df_9101['контрагент'].astype('string')
# -------------------КОНЕЦ Добавим доп признак (столбец "объект для изм ппа") для Изменения ППА-----------------------


# -------------------# Вид связи -----------------------
# группа_ка и сегмент_ка (из group_companies_df по контрагенту)
group_unique = group_companies_df.drop_duplicates(subset='ВариантыНазвания')
        
mapping_group = group_unique.set_index('ВариантыНазвания')['ВидСвязиКА'].astype('string')
# Расширяем маппинг: если ключа нет → '3 лица', но 'не_указано' → 'не_указано'
mapping_group_extended = {**mapping_group, 'не_указано': 'не_указано'}

mapping_segment_ka = group_unique.set_index('ВариантыНазвания')['сегмент'].astype('string')
# Расширяем маппинг: если ключа нет → '3 лица', но 'не_указано' → 'не_указано'
mapping_segment_ka_extended = {**mapping_segment_ka, 'не_указано': 'не_указано'}
        
df_9101['группа_ка'] = (
    df_9101['контрагент']
    .map(mapping_group_extended)
    .fillna('3 лица')
    .astype('string')
)
df_9101['сегмент_ка'] = (
    df_9101['контрагент']
    .map(mapping_segment_ka_extended)
    .fillna('3 лица')
    .astype('string'))

segment_company = companies_df.loc[companies_df['сокращенное_наименование_компании'] == name_company, 'сегмент'].values[0]

df_9101['сегмент'] = segment_company
df_9101['сегмент'] = df_9101.loc[:, 'сегмент'].astype('string')

df_9101['вид_связи'] = calculate_connection_type(df_9101)

In [11]:
mask_a = (df_9101['контрагент'] != 'не_указано')
mask_b = (df_9101['группа_ка'] == 'не_указано')
df_9101[mask_a & mask_b].empty

True

In [12]:
mask_a = (df_9101['контрагент'] == 'не_указано')
mask_b = (df_9101['группа_ка'] != 'не_указано')
df_9101[mask_a & mask_b].empty

True

In [13]:
# =========================================================================
# ЗАДАЧА: Уменьшение доходов  по статьям, связанным с контрагентами, на сумму НДС
# =========================================================================

# Фильтруем только строки с видами доходов/расходов, связанными с контрагентами

# ASSET_SALE_TYPES = ['Продажа прочего имущества', 'Продажа основных средств', 'Аренда']
# ASSET_SALE_TYPES = df_9101.loc[df_9101['Корр.счет'].str.startswith(CONTRACTOR_ACCOUNTS), 'вид_дохода_расхода'].unique().tolist()

# в доходах берем статьи, где корр. счета - счета учета расчетов в контрагентами
one_set = set(df_9101.loc[df_9101['Корр.счет'].isin(CONTRACTOR_ACCOUNTS), 'вид_дохода_расхода'].unique())

# в расходах наоборот, берем статьи, где корр. счета - это не счета учета расчетов в контрагентами,
# это должны быть корр.счета - стоимость реализованных/переданных контрагентам активов, получим эти строки путем пересечения множеств
# т.е. получим строки со статьями и в доходах и расходах
too_set = set(df_9102.loc[~df_9102['Корр.счет'].isin(CONTRACTOR_ACCOUNTS), 'вид_дохода_расхода'].unique())
ASSET_SALE_TYPES = list(one_set & too_set)

df_9101_assets = df_9101[
    df_9101['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
].copy()

df_9102_assets = df_9102[
    df_9102['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
].copy()

# logger.debug(
#     f"Продажа активов: {len(df_9101_assets)} строк доходов, "
#     f"{len(df_9102_assets)} строк расходов"
# )

print(
    f"Доходы/Расходы от контрагентов: {len(df_9101_assets)} строк доходов, "
    f"{len(df_9102_assets)} строк расходов"
)

# Выделяем НДС из df_9102 (Корр.счет начинается с "68.02")
mask_vat = df_9102_assets['Корр.счет'].astype(str).str.startswith(NDS_ACCOUNTS, na=False)
df_9102_vat = df_9102_assets[mask_vat].copy()

# Суммируем НДС по Документу (на случай нескольких записей по 68 счету)
vat_by_doc = (
    df_9102_vat
    .groupby('Документ', as_index=False)['оборот, тыс.ед.']
    .sum()
    .rename(columns={'оборот, тыс.ед.': 'ндс_тыс_ед'})
)

# logger.debug(
#     f"Найдено {len(vat_by_doc)} документов с НДС, "
#     f"сумма НДС={vat_by_doc['ндс_тыс_ед'].sum():,.2f} тыс.ед."
# )

print(
    f"Найдено {len(vat_by_doc)} документов с НДС, "
    f"сумма НДС={vat_by_doc['ндс_тыс_ед'].sum():,.2f} тыс.ед."
)

# Объединяем выручку с НДС через merge
df_9101_assets = df_9101_assets.merge(
    vat_by_doc, 
    on='Документ', 
    how='left'
)

# Заполняем NaN нулями для документов без НДС
df_9101_assets['ндс_тыс_ед'] = df_9101_assets['ндс_тыс_ед'].fillna(0)

# Уменьшаем выручку на НДС (доходы у нас со знаком минус, расходы - плюс),
# поэтому складываем
df_9101_assets['оборот, тыс.ед.'] = (
    df_9101_assets['оборот, тыс.ед.'] + df_9101_assets['ндс_тыс_ед']
)

# Логируем статистику
adjusted_count = (df_9101_assets['ндс_тыс_ед'] > 0).sum()
total_vat = df_9101_assets['ндс_тыс_ед'].sum()
# logger.debug(
#     f"Скорректировано {adjusted_count} строк выручки, "
#     f"сумма вычтенного НДС={total_vat:,.2f} тыс.ед."
# )
print(
    f"Скорректировано {adjusted_count} строк выручки, "
    f"сумма вычтенного НДС={total_vat:,.2f} тыс.ед."
)

# Обновляем df_9101: заменяем строки на скорректированные
#    (остальные строки остаются без изменений)
mask_assets_in_9101 = df_9101['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
df_9101_result = pd.concat([
    df_9101[~mask_assets_in_9101],  # Все кроме доходов/расходов от контрагентов
    df_9101_assets.drop(columns=['ндс_тыс_ед'])  # Скорректированные (без служебного столбца)
], ignore_index=True)

# Удаляем строки с НДС из части df_9102, относящейся к продаже активов
df_9102_assets_no_vat = df_9102_assets[~mask_vat].copy()

# Создаем маску для ИСХОДНОГО df_9102, чтобы отделить строки, не связанные с активами
mask_assets_in_original_9102 = df_9102['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)

# Объединяем:
# 1. Все исходные строки, НЕ относящиеся к продаже активов (остаются без изменений)
# 2. Строки продажи активов, из которых мы исключили НДС
df_9102_result = pd.concat([
    df_9102[~mask_assets_in_original_9102],  
    df_9102_assets_no_vat                    
], ignore_index=True)

# Явное приведение типов к string (на случай, если concat сломал)
text_cols = ['Документ', 'Корр.счет', 'счет', 'доход_расход', 
             'вид_дохода_расхода', 'контрагент']
for col in text_cols:
    if col in df_9101_result.columns:
        df_9101_result[col] = df_9101_result[col].astype('string')
    if col in df_9102_result.columns:
        df_9102_result[col] = df_9102_result[col].astype('string')

# logger.info(
#     f"✓ Обработка НДС завершена: df_9101 ({len(df_9101_result)} строк), "
#     f"df_9102 ({len(df_9102_result)} строк)"
# )
print(
    f"✓ Обработка НДС завершена: df_9101 ({len(df_9101_result)} строк), "
    f"df_9102 ({len(df_9102_result)} строк)"
)

Доходы/Расходы от контрагентов: 2191 строк доходов, 5686 строк расходов
Найдено 1595 документов с НДС, сумма НДС=55,634.68 тыс.ед.
Скорректировано 1565 строк выручки, сумма вычтенного НДС=47,454.41 тыс.ед.
✓ Обработка НДС завершена: df_9101 (10179 строк), df_9102 (67364 строк)

In [14]:
mask_a = (df_9101_result['контрагент'] != 'не_указано')
mask_b = (df_9101_result['группа_ка'] == 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [15]:
mask_a = (df_9101_result['контрагент'] == 'не_указано')
mask_b = (df_9101_result['группа_ка'] != 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [16]:
# =========================================================================
# ЗАДАЧА: Подтягивание контрагентов из df_9101 в df_9102
# (только для строк, сваязанных с контрагентами)
# =========================================================================

# Маски для фильтрации

mask_assets_9101 = df_9101_result['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
mask_assets_9102 = df_9102_result['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)

# Создаём маппинг Документ → контрагент
contractor_mapping = (
    df_9101_result.loc[mask_assets_9101, ['Документ', 'контрагент']]
    .drop_duplicates(subset='Документ', keep='first')
    .set_index('Документ')['контрагент']
)

connection_mapping = (
    df_9101_result.loc[mask_assets_9101, ['Документ', 'вид_связи']]
    .drop_duplicates(subset='Документ', keep='first')
    .set_index('Документ')['вид_связи']
)


# Проверка: нет ли документов с разными покупателями в df_9101
docs_with_multiple_buyers = (
    df_9101_result.loc[mask_assets_9101]
    .groupby('Документ')['контрагент']
    .nunique()
)

problem_docs = docs_with_multiple_buyers[docs_with_multiple_buyers > 1]

if len(problem_docs) > 0:
    # logger.warning(
    #     f"⚠️ Обнаружено {len(problem_docs)} документов с разными покупателями "
    #     f"в df_9101 (продажа активов): {list(problem_docs.index[:5])}..."
    # )
    print(
        f"⚠️ Обнаружено {len(problem_docs)} документов с разными покупателями "
        # f"в df_9101 (продажа активов): {list(problem_docs.index[:5])}..."
    )
    for i in list(problem_docs.index[:]):
        print(i)

# Подтягиваем контрагентов
mask_unspecified = (
    mask_assets_9102 &
    (df_9102_result['контрагент'] == 'не_указано')
)

mapped_contractors = df_9102_result.loc[mask_unspecified, 'Документ'].map(contractor_mapping)

# Заменяем только там, где удалось подтянуть значение
df_9102_result.loc[mask_unspecified, 'контрагент'] = np.where(
    mapped_contractors.notna(),
    mapped_contractors,
    'не_указано'
)
# Подтягиваем вид_связи
mapped_connections = df_9102_result.loc[mask_unspecified, 'Документ'].map(connection_mapping)

# Если столбца 'вид_связи' ещё нет в df_9102 — создаём с NaN
if 'вид_связи' not in df_9102_result.columns:
    df_9102_result['вид_связи'] = pd.NA

df_9102_result.loc[mask_unspecified, 'вид_связи'] = np.where(
    mapped_connections.notna(),
    mapped_connections,
    df_9102_result.loc[mask_unspecified, 'вид_связи']  # оставить как было
)

# Явное приведение к string
df_9102_result['контрагент'] = df_9102_result['контрагент'].astype('string')
df_9102_result['вид_связи'] = df_9102_result['вид_связи'].astype('string')

# 6. Статистика
replaced_contractors = mapped_contractors.notna().sum()
replaced_connections = mapped_connections.notna().sum()

# logger.debug(
#     f"Подтягивание из df_9101: "
#     f"{replaced_contractors} контрагентов, "
#     f"{replaced_connections} вид_связи"
# )
print(
    f"Подтягивание из df_9101: "
    f"{replaced_contractors} контрагентов, "
    f"{replaced_connections} вид_связи"
)

# Явное приведение к string (np.where часто возвращает object)
df_9102_result['контрагент'] = df_9102_result['контрагент'].astype('string')

# Статистика
replaced_count = mapped_contractors.notna().sum()
not_found_count = mapped_contractors.isna().sum()
total_assets = mask_assets_9102.sum()

# logger.debug(
#     f"Подтягивание контрагентов для продажи активов: "
#     f"обработано {total_assets} строк расходов, "
#     f"{replaced_count} обновлено, "
#     f"{not_found_count} документов не найдено в df_9101"
# )
print(
    f"Подтягивание контрагентов для продажи активов: "
    f"обработано {total_assets} строк расходов, "
    f"{replaced_count} обновлено, "
    f"{not_found_count} документов не найдено в df_9101"
)

⚠️ Обнаружено 5 документов с разными покупателями
Операция (бухгалтерский и налоговый учет) 00000000014 от 10.01.2025 12:00:00
Операция (бухгалтерский и налоговый учет) 00000000016 от 10.01.2025 12:00:01
Операция (бухгалтерский и налоговый учет) 00000000123 от 30.01.2025 16:45:44
Операция (бухгалтерский и налоговый учет) 00000000303 от 01.04.2025 12:00:01
Операция (бухгалтерский и налоговый учет) 00000001001 от 01.12.2025 12:00:03
Подтягивание из df_9101: 323 контрагентов, 323 вид_связи
Подтягивание контрагентов для продажи активов: обработано 4091 строк расходов, 323 обновлено, 3337 документов не найдено в df_9101

In [17]:
mask_a = (df_9101_result['контрагент'] != 'не_указано')
mask_b = (df_9101_result['группа_ка'] == 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [18]:
mask_a = (df_9101_result['контрагент'] == 'не_указано')
mask_b = (df_9101_result['группа_ка'] != 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [19]:
# =========================================================================
# РАСПРЕДЕЛЕНИЕ "ОСИРОТЕВШИХ" РАСХОДОВ (по статьям, связанным с контрагентами) ПРОПОРЦИОНАЛЬНО ВЫРУЧКЕ
# =========================================================================

# Фильтруем только строки по статьям, связанным с контрагентами
mask_9101_assets = df_9101_result['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
mask_9102_assets = df_9102_result['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)

df_9101_assets = df_9101_result[mask_9101_assets].copy()
df_9102_assets = df_9102_result[mask_9102_assets].copy()

# Определяем документы-сироты (есть в df_9102, но нет в df_9101)
docs_in_9101 = set(df_9101_assets['Документ'].unique())
docs_in_9102 = set(df_9102_assets['Документ'].unique())
orphan_docs = docs_in_9102 - docs_in_9101

print(
    f"Продажа активов или аренда: {len(docs_in_9101)} документов в доходах, "
    f"{len(docs_in_9102)} документов в расходах, "
    f"{len(orphan_docs)} документов-сирот"
)
# logger.debug(
#     f"Продажа активов: {len(docs_in_9101)} документов в доходах, "
#     f"{len(docs_in_9102)} документов в расходах, "
#     f"{len(orphan_docs)} документов-сирот"
# )

# Разделяем df_9102 на привязанные и осиротевшие
mask_orphan = df_9102_assets['Документ'].isin(orphan_docs)
df_9102_attached = df_9102_assets[~mask_orphan].copy()
df_9102_orphan = df_9102_assets[mask_orphan].copy()

# =========================================================================
# РАСПРЕДЕЛЕНИЕ ОСИРОТЕВШИХ ДОКУМЕНТОВ
# =========================================================================

if not df_9102_orphan.empty:
    # Создаём маппинг контрагент → вид_связи из df_9101
    # Берём первое вхождение на случай, если один контрагент в нескольких документах
    contractor_to_connection = (
        df_9101_assets[['контрагент', 'вид_связи']]
        .drop_duplicates(subset='контрагент', keep='first')
        .set_index('контрагент')['вид_связи']
    )
    
    # Расчёт долей выручки каждого контрагента в рамках вид_дохода_расхода
    # Используем transform для сохранения индекса
    revenue_by_type = df_9101_assets.groupby('вид_дохода_расхода')['оборот, тыс.ед.'].transform('sum')
    df_9101_assets['доля_контрагента'] = df_9101_assets['оборот, тыс.ед.'] / revenue_by_type
    
    # Агрегируем: на каждого контрагента в рамках вид_дохода_расхода — его суммарная доля
    # (контрагент может быть в нескольких документах продажи)
    contractor_share = (
        df_9101_assets.groupby(['вид_дохода_расхода', 'контрагент'], as_index=False)
        ['доля_контрагента'].sum()
    )
    
    # удаляем 'контрагент' перед merge, чтобы не было суффиксов _x/_y
    df_9102_orphan = df_9102_orphan.drop(columns=['контрагент'], errors='ignore')
    # Cross-join: каждый документ-сирота × каждый контрагент (в рамках вид_дохода_расхода)
    # Добавляем ключ для join по вид_дохода_расхода
    df_9102_orphan_dist = df_9102_orphan.merge(
        contractor_share,
        on='вид_дохода_расхода',
        how='inner'  # только те вид_дохода_расхода, по которым есть выручка
    )
    
    # Распределяем оборот пропорционально долям
    df_9102_orphan_dist['оборот_распределенный'] = (
        df_9102_orphan_dist['оборот, тыс.ед.'] * df_9102_orphan_dist['доля_контрагента']
    )

    # Подтягиваем вид_связи из маппинга
    df_9102_orphan_dist['вид_связи'] = (
        df_9102_orphan_dist['контрагент'].map(contractor_to_connection).astype('string')
    )
    
    # Финальная очистка
    df_9102_orphan_dist = df_9102_orphan_dist.drop(
        columns=['оборот, тыс.ед.', 'доля_контрагента']
    )
    df_9102_orphan_dist = df_9102_orphan_dist.rename(
        columns={'оборот_распределенный': 'оборот, тыс.ед.'}
    )
    
    # Обновляем контрагент (в df_9102_orphan он был 'не_указано', теперь — конкретный)
    # Убираем служебные столбцы и оставляем только нужные
    df_9102_orphan_dist = df_9102_orphan_dist.drop(
        columns=['контрагент_x'], errors='ignore'  # если был дубль после merge
    )
    
    # logger.debug(
    #     f"Распределено {len(df_9102_orphan)} осиротевших строк "
    #     f"на {len(df_9102_orphan_dist)} строк по {contractor_share['контрагент'].nunique()} контрагентам"
    # )
    print(
        f"Распределено {len(df_9102_orphan)} осиротевших строк "
        f"на {len(df_9102_orphan_dist)} строк по {contractor_share['контрагент'].nunique()} контрагентам"
    )
else:
    df_9102_orphan_dist = pd.DataFrame()
    # logger.debug("Осиротевших документов не найдено")
    print("Осиротевших документов не найдено")

# =========================================================================
# ОБЪЕДИНЕНИЕ РЕЗУЛЬТАТОВ
# =========================================================================

# Собираем обратно: привязанные + распределённые
df_9102_assets_updated = pd.concat(
    [df_9102_attached, df_9102_orphan_dist],
    ignore_index=True
)

# Проверка сходимости: сумма по осиротевшим документам не должна измениться
if not df_9102_orphan.empty and not df_9102_orphan_dist.empty:
    sum_before = df_9102_orphan['оборот, тыс.ед.'].sum()
    sum_after = df_9102_orphan_dist['оборот, тыс.ед.'].sum()
    difference = abs(sum_before - sum_after)
    
    if difference > 0.01:  # допуск на округление
        # logger.warning(
        #     f"⚠️ Расхождение при распределении: было {sum_before:,.2f}, "
        #     f"стало {sum_after:,.2f}, разница {difference:,.2f} тыс.ед."
        # )
        print(
            f"⚠️ Расхождение при распределении: было {sum_before:,.2f}, "
            f"стало {sum_after:,.2f}, разница {difference:,.2f} тыс.ед."
        )
    else:
        # logger.debug(f"✓ Сумма осиротевших документов сохранена: {sum_after:,.2f}")
        print(f"✓ Сумма осиротевших документов сохранена: {sum_after:,.2f}")

# Явное приведение текстовых столбцов к string (на случай object после concat)
text_cols = ['Документ', 'Корр.счет', 'счет', 'доход_расход', 
             'вид_дохода_расхода', 'контрагент', 'вид_связи']
for col in text_cols:
    if col in df_9102_assets_updated.columns:
        df_9102_assets_updated[col] = df_9102_assets_updated[col].astype('string')

# Обновляем основной df_9102: заменяем строки продажи активов на обновлённые
# (остальные строки остаются без изменений)
mask_assets_in_main = df_9102_result['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
df_9102_result = pd.concat([
    df_9102_result[~mask_assets_in_main],        # Все кроме продажи активов
    df_9102_assets_updated                 # Обновлённые строки
], ignore_index=True)

# logger.info(
#     f"✓ Распределение завершено: df_9102 = {len(df_9102)} строк "
#     f"(в т.ч. {len(df_9102_assets_updated)} по продаже активов)"
# )
print(
    f"✓ Распределение завершено: df_9102 = {len(df_9102)} строк "
    f"(в т.ч. {len(df_9102_assets_updated)} по продаже активов)"
)

Продажа активов или аренда: 2086 документов в доходах, 1556 документов в расходах, 1316 документов-сирот
Распределено 3713 осиротевших строк на 32144 строк по 226 контрагентам
✓ Сумма осиротевших документов сохранена: 233,270.53
✓ Распределение завершено: df_9102 = 68959 строк (в т.ч. 32522 по продаже активов)

In [20]:
mask_a = (df_9101_result['контрагент'] == 'не_указано')
mask_b = (df_9101_result['группа_ка'] != 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [21]:
mask_a = (df_9101_result['контрагент'] != 'не_указано')
mask_b = (df_9101_result['группа_ка'] == 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [22]:
# --------------------Обслуживание кредитных линий для 91.01-------------------------------
# Вытащить из субконто 97 счета РБП, это рбп по кредитным линиям. По этим РБП достать из справочника "КредитОбслуж" КА -> Сегмент КА -> Вид связи
# Обслужиание кредитных линий - это списание в расходы капитализации услуг УК, банков и страховых с 97 счета
# Отфильтруем данные по вид_дохода_расхода и корр счету
mask = ((df_9101_result['вид_дохода_расхода'] == 'Кредитное обслуживание и расходы по открытию кредитных линий')
        & (df_9101_result['Корр.счет'].str.startswith('97')))

# субконто у корр.счета 97 это рбп по кредитным линиям. По этому рбп через справочник мы вытащим контрагента
# создадим столбец 'рбп_кредитные_линии'
df_9101_result['рбп_кредитные_линии'] = df_9101_result.loc[:, 'Субконто Дт_1'].where(mask, 'не_указано')

# справочник по рбп кредитные линии отфильтрованный по компании:
reference_rbp_credit = reference_rbp_credit.loc[reference_rbp_credit['компания'] == name_company]

# Маппинг из справочника КредитОбслуж (с защитой от дубликатов)
mapping_rbp_credit = (
    reference_rbp_credit
    .drop_duplicates(subset='рбп_кредитные_линии')
    .set_index('рбп_кредитные_линии')['контрагент'])

# Выполняем маппинг во временный столбец или переменную
mapped_values = df_9101_result.loc[mask, 'рбп_кредитные_линии'].map(mapping_rbp_credit)

In [23]:
mask_a = (df_9101_result['контрагент'] != 'не_указано')
mask_b = (df_9101_result['группа_ка'] == 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [24]:
mask_a = (df_9101_result['контрагент'] == 'не_указано')
mask_b = (df_9101_result['группа_ка'] != 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [25]:
# Проверяем, есть ли пропуски (NaN) после маппинга
if mapped_values.isna().any():
    # Находим уникальные значения РБП, для которых не нашлось соответствия
    missing_rbps = df_9101_result.loc[mapped_values.isna(), 'рбп_кредитные_линии'].unique()
    
    # Выводим список отсутствующих значений
    print(f"❌ Ошибка: Не найдены следующие РБП в справочнике Кредитное обслуживание:")
    for rbp in missing_rbps:
        print(f"   - {rbp}")
        
    # Вызываем ошибку с понятным сообщением
    raise ValueError("Обновите справочник Кредитное обслуживание")

# Если ошибок нет, обновляем основной столбец
df_9101_result.loc[mask, 'контрагент'] = mapped_values.astype('string')
df_9101_result.loc[mask, 'группа_ка'] = df_9101_result.loc[mask, 'контрагент'].map(mapping_group).fillna('3 лица').astype('string')
df_9101_result.loc[mask, 'сегмент_ка'] = df_9101_result.loc[mask, 'контрагент'].map(mapping_segment_ka).fillna('3 лица').astype('string')
df_9101_result.loc[mask, 'вид_связи'] = calculate_connection_type(df_9101_result)

In [26]:
mask_a = (df_9101_result['контрагент'] == 'не_указано')
mask_b = (df_9101_result['группа_ка'] != 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [27]:
mask_a = (df_9101_result['контрагент'] != 'не_указано')
mask_b = (df_9101_result['группа_ка'] == 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [28]:
# --------------------Обслуживание кредитных линий для 91.02-------------------------------
# Вытащить из субконто 97 счета РБП, это рбп по кредитным линиям. По этим РБП достать из справочника "КредитОбслуж" КА -> Сегмент КА -> Вид связи
# Обслужиание кредитных линий - это списание в расходы капитализации услуг УК, банков и страховых с 97 счета
# Отфильтруем данные по вид_дохода_расхода и корр счету
mask = ((df_9102_result['вид_дохода_расхода'] == 'Кредитное обслуживание и расходы по открытию кредитных линий')
        & (df_9102_result['Корр.счет'].str.startswith('97')))

# субконто у корр.счета 97 это рбп по кредитным линиям. По этому рбп через справочник мы вытащим контрагента
# создадим столбец 'рбп_кредитные_линии'
df_9102_result['рбп_кредитные_линии'] = df_9102_result.loc[:, 'Субконто Кт_1'].where(mask, 'не_указано')

# справочник по рбп кредитные линии отфильтрованный по компании:
reference_rbp_credit = reference_rbp_credit.loc[reference_rbp_credit['компания'] == name_company]

# Маппинг из справочника КредитОбслуж (с защитой от дубликатов)
mapping_rbp_credit = (
    reference_rbp_credit
    .drop_duplicates(subset='рбп_кредитные_линии')
    .set_index('рбп_кредитные_линии')['контрагент'])

# Выполняем маппинг во временный столбец или переменную
mapped_values = df_9102_result.loc[mask, 'рбп_кредитные_линии'].map(mapping_rbp_credit)

# Проверяем, есть ли пропуски (NaN) после маппинга
if mapped_values.isna().any():
    # Находим уникальные значения РБП, для которых не нашлось соответствия
    missing_rbps = df_9102_result.loc[mapped_values.isna(), 'рбп_кредитные_линии'].unique()
    
    # Выводим список отсутствующих значений
    logger.error("❌ Ошибка: Не найдены следующие РБП в справочнике Кредитное обслуживание:")
    for rbp in missing_rbps:
        print(f"   - {rbp}")
        
    # Вызываем ошибку
    raise ValueError("Обновите справочник Кредитное обслуживание")

# Если ошибок нет, обновляем основной столбец
df_9102_result.loc[mask, 'контрагент'] = mapped_values.astype('string')

mask_credit = df_9102_result['вид_дохода_расхода'] == 'Кредитное обслуживание и расходы по открытию кредитных линий'
mask_missing = df_9102_result['контрагент'] == 'не_указано'

missing_list = (
    df_9102_result
    .loc[mask_credit & mask_missing, 'рбп_кредитные_линии']
    .unique()
    .tolist()
)
if missing_list:
    print(
        f"Обнаружены РБП по кредитным линиям, отсутствующие в справочнике "
        f"КредитОбслуж либо по которым нет контрагента ({len(missing_list)} шт.):\n"
        + "\n".join(f"  - {item}" for item in missing_list)
    )
    raise ValueError("Обнаружены РБП по кредитным линиям, отсутствующие в справочнике ")
# if missing_list:
#     logger.warning(
#         f"Обнаружены РБП по кредитным линиям, отсутствующие в справочнике "
#         f"КредитОбслуж либо по которым нет контрагента ({len(missing_list)} шт.):\n"
#         + "\n".join(f"  - {item}" for item in missing_list)
#     )

df_9102_result['сегмент'] = segment_company
df_9102_result['сегмент'] = df_9102_result.loc[:, 'сегмент'].astype('string')
        
df_9102_result.loc[mask, 'группа_ка'] = df_9102_result.loc[mask, 'контрагент'].map(mapping_group).fillna('3 лица').astype('string')
df_9102_result.loc[mask, 'сегмент_ка'] = df_9102_result.loc[mask, 'контрагент'].map(mapping_segment_ka).fillna('3 лица').astype('string')

# 1. Берем только те строки, которые попали под маску
df_subset = df_9102_result.loc[mask]

# 2. Рассчитываем вид_связи только для этого подмножества
# Функция вернет Series с индексами, совпадающими с df_subset
connection_types = calculate_connection_type(df_subset)

# 3. Записываем результат обратно в основной датафрейм по соответствующим индексам
df_9102_result.loc[mask, 'вид_связи'] = connection_types.values

In [29]:
mask_a = (df_9101_result['контрагент'] != 'не_указано')
mask_b = (df_9101_result['группа_ка'] == 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [30]:
mask_a = (df_9101_result['контрагент'] == 'не_указано')
mask_b = (df_9101_result['группа_ка'] != 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [31]:
mask_a = (df_9102_result['контрагент'] == 'не_указано')
mask_b = (df_9102_result['группа_ка'] != 'не_указано')
df_9102_result[mask_a & mask_b].empty

True

In [32]:
mask_a = (df_9102_result['контрагент'] != 'не_указано')
mask_b = (df_9102_result['группа_ка'] == 'не_указано')
df_9102_result[mask_a & mask_b].empty

True

In [33]:
#----------------------------------ПРОЦЕНТНЫЕ РАСХОДЫ---------------------------------------------------
# Отфильтруем строки, чтобы КА == не_указано, а вид_дохода_расхода isin INTEREST_EXPENSES
mask_interest = (df_9102_result['вид_дохода_расхода'].isin(INTEREST_EXPENSES)) & (df_9102_result['контрагент'] == 'не_указано')

# Маппинг из справочника ППА (с защитой от дубликатов)
mapping_ppa = (
    reference_ppa_df
    .drop_duplicates(subset='рбп')
    .set_index('рбп')['контрагент']
)
df_9102_result['рбп_проценты'] = df_9102_result.loc[:, 'Субконто Кт_1'].where(mask_interest, 'не_указано')
mapped = df_9102_result['рбп_проценты'].map(mapping_ppa)
mapped = mapped.fillna(df_9102_result['контрагент'])

# Если mask_interest == True, оставляем старое значение. 
# Если False, берем значение из mapped.
df_9102_result['контрагент'] = df_9102_result['контрагент'].where(
    ~mask_interest,  # Инвертируем маску: где НЕ проценты, там оставляем как было
    mapped           # Где проценты (маска False), туда подставляем mapped
)

if not df_9102_result.loc[(df_9102_result['вид_дохода_расхода'].isin(INTEREST_EXPENSES)) & (df_9102_result['контрагент'].isin(['не_указано']))].empty:
    print('В справочнике ППА в поле "рбп" отсутствуют следующие значения:')
    print(df_9102_result.loc[(df_9102_result['вид_дохода_расхода'].isin(INTEREST_EXPENSES)) & (df_9102_result['контрагент'].isin(['не_указано'])), 'рбп_проценты'].unique())
    raise ValueError('В справочнике ППА в поле "рбп" отсутствуют значения')
# -------------------# Вид связи -----------------------
# группа_ка и сегмент_ка (из group_companies_df по контрагенту)
group_unique = group_companies_df.drop_duplicates(subset='ВариантыНазвания')
        
mapping_group = group_unique.set_index('ВариантыНазвания')['ВидСвязиКА'].astype('string')
mapping_segment_ka = group_unique.set_index('ВариантыНазвания')['сегмент'].astype('string')
        
df_9102_result.loc[mask_interest, 'группа_ка'] = df_9102_result.loc[mask_interest,'контрагент'].map(mapping_group).fillna('3 лица').astype('string')
df_9102_result.loc[mask_interest,'сегмент_ка'] = df_9102_result.loc[mask_interest,'контрагент'].map(mapping_segment_ka).fillna('3 лица').astype('string')

# df_9102_result['вид_связи'] = calculate_connection_type(df_9102_result)

# Берем только те строки, которые попали под маску
df_subset = df_9102_result.loc[mask_interest]

# Рассчитываем вид_связи только для этого подмножества
# Функция вернет Series с индексами, совпадающими с df_subset
connection_types = calculate_connection_type(df_subset)

# Записываем результат обратно в основной датафрейм по соответствующим индексам
df_9102_result.loc[mask_interest, 'вид_связи'] = connection_types.values

In [34]:
mask_a = (df_9101_result['контрагент'] != 'не_указано')
mask_b = (df_9101_result['группа_ка'] == 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [35]:
mask_a = (df_9101_result['контрагент'] == 'не_указано')
mask_b = (df_9101_result['группа_ка'] != 'не_указано')
df_9101_result[mask_a & mask_b].empty

True

In [36]:
mask_a = (df_9102_result['контрагент'] == 'не_указано')
mask_b = (df_9102_result['группа_ка'] != 'не_указано')
df_9102_result[mask_a & mask_b].empty

True

In [37]:
mask_a = (df_9102_result['контрагент'] != 'не_указано')
mask_b = (df_9102_result['группа_ка'] == 'не_указано')
df_9102_result[mask_a & mask_b].empty

True

In [38]:
mask_l = (df_9102_result['контрагент']=="не_указано")
mask_m = (df_9102_result['группа_ка']=="3 лица")
df_9102_result[mask_l & mask_m].head()

Empty DataFrame
Columns: [Имя_файла, Дата, Документ, счет, Корр.счет, оборот, тыс.ед., Содержание_1, Содержание_2, доход_расход, Субконто Кт_1, Субконто Кт_2, Субконто Кт_3, контрагент, вид_дохода_расхода, вид_связи, рбп_кредитные_линии, сегмент, группа_ка, сегмент_ка, рбп_проценты]
Index: []

In [39]:
# Объединяем доходы и расходы в один датафрейм
df_final = pd.concat([df_9101_result, df_9102_result], ignore_index=True)
df_final['счет'] = df_final['счет'].astype(str).str.split('.').str[:2].str.join('.')
df_final['счет'] = df_final.loc[:, 'счет'].astype('string')

In [40]:
# группируем
text_cols = [
    'счет', 'вид_дохода_расхода', 'доход_расход', 'контрагент',
    'объект для изм ппа', 'группа_ка', 'сегмент_ка', 'сегмент',
    'вид_связи', 'рбп_кредитные_линии', 'рбп_проценты'
]

# Убедимся, что все текстовые столбцы действительно строковые и без NaN
for col in text_cols:
    if col in df_final.columns:
        df_final[col] = df_final[col].fillna('не_указано').astype('string')

# Группируем
df_concat = df_final.groupby(text_cols, as_index=False)['оборот, тыс.ед.'].sum()

df_concat.to_excel('12.xlsx')

'контрагент',
'ном_группа',
'счет',
'оборот, тыс.ед.',
'доход_расход',
 'вид_дохода_расхода'
 'сегмент'
 'группа_ка'
 'сегмент_ка'
  'вид_связ],

In [42]:
mask_a = (df_9102_result['контрагент'] != 'не_указано')
mask_b = (df_9102_result['группа_ка'] == 'не_указано')
df_9102_result[mask_a & mask_b]

Empty DataFrame
Columns: [Имя_файла, Дата, Документ, счет, Корр.счет, оборот, тыс.ед., Содержание_1, Содержание_2, доход_расход, Субконто Кт_1, Субконто Кт_2, Субконто Кт_3, контрагент, вид_дохода_расхода, вид_связи, рбп_кредитные_линии, сегмент, группа_ка, сегмент_ка, рбп_проценты]
Index: []

In [43]:
# Группируем
text_cols = [
    'счет', 'вид_дохода_расхода', 'доход_расход', 'контрагент',
    'группа_ка', 'сегмент_ка', 'сегмент',
    'вид_связи', 'рбп_кредитные_линии', 'рбп_проценты'
]
df_concat = df_9102_result.groupby(text_cols, as_index=False)['оборот, тыс.ед.'].sum()

df_concat.to_excel('12.xlsx')

In [44]:
# key_cols = ['счет', 'вид_дохода_расхода', 'сегмент', 'вид_связи']

# ref_keyed = (
#     reference_df
#     .drop_duplicates(subset=key_cols)
#     .set_index(key_cols)['счет_фо']
# )

# df_final['счет_фо'] = (
#     df_final.set_index(key_cols).index
#     .map(ref_keyed)
#     .values
# )

# # Находим дубликаты ключей в справочнике
# duplicates = (
#     reference_df
#     .groupby(key_cols)['счет_фо']
#     .nunique()
#     .reset_index()
# )
# duplicates = duplicates[duplicates['счет_фо'] > 1]

# print(f"Ключей с несколькими счет_фо: {len(duplicates)}")
# if len(duplicates) > 0:
#     print(duplicates.head(10))


# unmatched = df_final['счет_фо'].isna().sum()
# total = len(df_final)
# print(f"Найдено совпадений: {total - unmatched} из {total}")
# print(f"Не найдено (NaN): {unmatched} ({unmatched/total*100:.1f}%)")

# if unmatched > 0:
#     print("\nПримеры строк без счет_фо:")
#     print(df_final[df_final['счет_фо'].isna()][key_cols].drop_duplicates().head(10))

In [60]:
'''
Обороты, формирующие прибыль до налогообложения, сформированы.
Для чистой прибыли нужно включить обороты, связанные с налогообложением прибыли (в т.ч. ОНА/ОНО). Пусть это будет блок "Налог на прибыль"
Также нужно учесть возможные движения за счет чистой прибыли, пусть это будет блок "Прочие"
'''

# загружаем отчет по проводкам по 99 счету
df99 = intermediate_data_df.loc[intermediate_data_df['Имя_файла']=='РЗК_отчпровод_99_2025_.txt']

# уберем субсчета, оставив только синтетические счета
df99.loc[:, 'Дт'] = df99.loc[:, 'Дт'].str[:2]
df99.loc[:, 'Кт'] = df99.loc[:, 'Кт'].str[:2]

# уберм обороты связанные с закрытием периода/реформацией баланса
mask_a = (df99['Дт'] == '99') & (df99['Кт'].isin(['90', '91', '84', '99']))
mask_b = (df99['Кт'] == '99') & (df99['Дт'].isin(['90', '91', '84', '99']))
df99 = df99.loc[~(mask_a | mask_b)]

# доходы (кредит по 99 счету) сделаем с минусом. расходы знак не меняем, он с плюсом. Переведем в тысячи.
mask_c = (df99['Кт']=='99')
df99['оборот, тыс.ед.'] = df99.loc[:, 'Сумма']/1000
df99.loc[mask_c, 'оборот, тыс.ед.'] = -df99.loc[mask_c, 'оборот, тыс.ед.']

# получим сумму налога на прибыль для блока "Налог на прибыль"
mask_d = ((df99['Дт'] == '68') & (df99['Кт'] == '99')) | ((df99['Дт'] == '99') & (df99['Кт'] == '68'))
main_task = df99.loc[mask_d, 'оборот, тыс.ед.'].sum()

# получим сумму прочих движений за чет чистой прибыли
main_value = df99.loc[~mask_d, 'оборот, тыс.ед.'].sum()

In [64]:
# mask = (df99['Дт'].str.startswith('99.02')) | (df99['Кт'].str.startswith('99.02'))
# df99[mask]

In [66]:
# df99_task = df99.loc[mask]

In [70]:

df99

,Имя_файла,Дата,Документ,Дт,Кт,Сумма,Содержание_1,Содержание_2,Субконто Дт_1,Субконто Дт_2,Субконто Кт_1,Субконто Кт_2,Субконто Кт_3,Субконто Дт_3
191399,РЗК_отчпровод_99_2025_.txt,2025-03-31 22:00:08,Операция (бухгалтерский и налоговый учет) 0000...,68,99,"42,050,129.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
191400,РЗК_отчпровод_99_2025_.txt,2025-03-31 22:00:08,Операция (бухгалтерский и налоговый учет) 0000...,99,68,"1,323,079.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
191407,РЗК_отчпровод_99_2025_.txt,2025-06-30 17:00:07,Операция (бухгалтерский и налоговый учет) 0000...,68,99,"71,044,937.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
191408,РЗК_отчпровод_99_2025_.txt,2025-06-30 17:00:07,Операция (бухгалтерский и налоговый учет) 0000...,99,68,"2,260,698.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
191411,РЗК_отчпровод_99_2025_.txt,2025-07-01 23:59:59,Операция (бухгалтерский и налоговый учет) 0000...,68,99,"-42,049,388.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
191412,РЗК_отчпровод_99_2025_.txt,2025-07-01 23:59:59,Операция (бухгалтерский и налоговый учет) 0000...,99,68,"-1,323,260.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
191417,РЗК_отчпровод_99_2025_.txt,2025-09-30 00:00:00,Операция (бухгалтерский и налоговый учет) 0000...,68,99,"93,017,209.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
191418,РЗК_отчпровод_99_2025_.txt,2025-09-30 00:00:00,Операция (бухгалтерский и налоговый учет) 0000...,99,68,"9,279,932.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
191425,РЗК_отчпровод_99_2025_.txt,2025-12-31 22:00:53,Операция (бухгалтерский и налоговый учет) 0000...,99,68,"3,895,323.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
191426,РЗК_отчпровод_99_2025_.txt,2025-12-31 22:00:53,Операция (бухгалтерский и налоговый учет) 0000...,68,99,"1,015,100.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [72]:
mask_c = (df99['Кт']=='99')
df99['оборот, тыс.ед.'] = df99.loc[:, 'Сумма']/1000
df99.loc[mask_c, 'оборот, тыс.ед.'] = -df99.loc[mask_c, 'оборот, тыс.ед.']
df99

,Имя_файла,Дата,Документ,Дт,Кт,Сумма,Содержание_1,Содержание_2,Субконто Дт_1,Субконто Дт_2,Субконто Кт_1,Субконто Кт_2,Субконто Кт_3,Субконто Дт_3,"оборот, тыс.ед."
191399,РЗК_отчпровод_99_2025_.txt,2025-03-31 22:00:08,Операция (бухгалтерский и налоговый учет) 0000...,68,99,"42,050,129.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"-42,050.13"
191400,РЗК_отчпровод_99_2025_.txt,2025-03-31 22:00:08,Операция (бухгалтерский и налоговый учет) 0000...,99,68,"1,323,079.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"1,323.08"
191407,РЗК_отчпровод_99_2025_.txt,2025-06-30 17:00:07,Операция (бухгалтерский и налоговый учет) 0000...,68,99,"71,044,937.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"-71,044.94"
191408,РЗК_отчпровод_99_2025_.txt,2025-06-30 17:00:07,Операция (бухгалтерский и налоговый учет) 0000...,99,68,"2,260,698.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"2,260.70"
191411,РЗК_отчпровод_99_2025_.txt,2025-07-01 23:59:59,Операция (бухгалтерский и налоговый учет) 0000...,68,99,"-42,049,388.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"42,049.39"
191412,РЗК_отчпровод_99_2025_.txt,2025-07-01 23:59:59,Операция (бухгалтерский и налоговый учет) 0000...,99,68,"-1,323,260.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"-1,323.26"
191417,РЗК_отчпровод_99_2025_.txt,2025-09-30 00:00:00,Операция (бухгалтерский и налоговый учет) 0000...,68,99,"93,017,209.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"-93,017.21"
191418,РЗК_отчпровод_99_2025_.txt,2025-09-30 00:00:00,Операция (бухгалтерский и налоговый учет) 0000...,99,68,"9,279,932.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"9,279.93"
191425,РЗК_отчпровод_99_2025_.txt,2025-12-31 22:00:53,Операция (бухгалтерский и налоговый учет) 0000...,99,68,"3,895,323.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"3,895.32"
191426,РЗК_отчпровод_99_2025_.txt,2025-12-31 22:00:53,Операция (бухгалтерский и налоговый учет) 0000...,68,99,"1,015,100.00",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"-1,015.10"

In [74]:
df99['оборот, тыс.ед.'].sum()

np.float64(-149642.21500000003)

In [8]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
})

# Получить значение ячейки по метке строки и имени столбца
val = df.loc[1, 'Age']

type(val)

numpy.int64