К полю "доход_расход" нужно подтянуть "вид_дохода_расхода" из Справочника "Меппинг_опу". По значениям вид_дохода_расхода создавать доп столбцы из значений Субконто.

Смотрим 91.01:

1. Переоценка ГП - доп столбцов выделять не нужно.
2. Премии покупателям - для 91.01 это скорее премии от поставщиков за выполнение планового объема закупок, доп столбцы не нужны (КА уже есть), но нужно определять вид связи и сегмент.
3. Аренда - доп столбцов выделять не нужно.
4. Изменение ППА - добавить доп признак (столбец "объект для изм ппа") для Изменения ППА - столбец с ППА, чтобы найти по нему КА из Справочника (лист "ППА")
5. Финансовый доход - доп столбцов выделять не нужно.
6. Продажа активов - вид_доход_расход "Продажа прочего имущества" и "Продажа основных средств" подтянуть КА для 91.02 из 91.01 по номеру операции. Выручку свернуть с НДС (68.08 91.02), распределить расходы 9102, по которым не нашелся Документ из 9101
7. Кредитное обслуживание. Вытащить из субконто 97 счета РБП, это рбп по кредитным линиям. По этим РБП достать из справочника "КредитОбслуж" КА -> Сегмент КА -> Вид связи

In [366]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:,.2f}'.format
CONTRACTOR_ACCOUNTS = ('58', '60', '62', '63', '66', '67', '75', '76')
PPA_ACCOUNTS = ('01.09', '02.01', '01.01')
name_company = "РЗК"

In [367]:
intermediate_data_df = pd.read_parquet('intermediate_data.parquet')

In [368]:
# Справочник Меппинг ОПУ
reference_df = pd.read_excel('C:/Users/a.karabedyan/Documents/PythonProject/decryption_collector_refactored_open_code/_REFERENCE_DATA/Справочники.xlsx', sheet_name='Меппинг_опу')

# Справочник ППА
reference_ppa_df = pd.read_excel('C:/Users/a.karabedyan/Documents/PythonProject/decryption_collector_refactored_open_code/_REFERENCE_DATA/Справочники.xlsx', sheet_name='ППА')

# Справочник Вид связи КА
group_companies_df = pd.read_excel('C:/Users/a.karabedyan/Documents/PythonProject/decryption_collector_refactored_open_code/_REFERENCE_DATA/Справочники.xlsx', sheet_name='ВидСвязиКА')

# Справочник компаний
companies_df = pd.read_excel('C:/Users/a.karabedyan/Documents/PythonProject/decryption_collector_refactored_open_code/_REFERENCE_DATA/Справочники.xlsx', sheet_name='КомпанииГруппы')

# Справочник рбп с кредитными лингиями
reference_rbp_credit = pd.read_excel('C:/Users/a.karabedyan/Documents/PythonProject/decryption_collector_refactored_open_code/_REFERENCE_DATA/Справочники.xlsx', sheet_name='КредитОбслуж')

In [369]:
# Выгружаем обороты по 91 и разделяем на субсчета
df_91_all = intermediate_data_df.loc[intermediate_data_df['Имя_файла'].str.contains('_91.0', na=False)]
df_9101 = df_91_all.loc[df_91_all['Кт'].str.startswith('91.01')]
df_9102 = df_91_all.loc[df_91_all['Дт'].str.startswith('91.02')]

In [370]:
# Общая обработка и 91.01, и 91.02

# 91.01
df_9101 = df_9101.rename(columns={'Субконто Кт_1': 'доход_расход', 'Сумма': 'оборот, тыс.ед.', 'Дт': 'Корр.счет', 'Кт': 'счет'})
mask = df_9101['Корр.счет'].astype(str).str.startswith(CONTRACTOR_ACCOUNTS, na=False)
df_9101['контрагент'] = df_9101['Субконто Дт_1'].where(mask, 'не_указано').astype('string')
df_9101['оборот, тыс.ед.'] = df_9101.loc[:, 'оборот, тыс.ед.'] / -1000

#91.02
df_9102 = df_9102.rename(columns={'Субконто Дт_1': 'доход_расход', 'Сумма': 'оборот, тыс.ед.', 'Кт': 'Корр.счет', 'Дт': 'счет'})
mask = df_9102['Корр.счет'].astype(str).str.startswith(CONTRACTOR_ACCOUNTS, na=False)
df_9102['контрагент'] = df_9102['Субконто Кт_1'].where(mask, 'не_указано').astype('string')
df_9102['оборот, тыс.ед.'] = df_9102.loc[:, 'оборот, тыс.ед.'] / 1000

# Создаём составной ключ в справочнике и в данных
reference_df['_key'] = reference_df['счет'].astype(str) + '_' + reference_df['доход_расход'].astype(str)

df_9101['_key'] = df_9101['счет'].astype(str).str[:5] + '_' + df_9101['доход_расход'].astype(str)
df_9102['_key'] = df_9102['счет'].astype(str).str[:5] + '_' + df_9102['доход_расход'].astype(str)

# Маппинг
mapping = reference_df.drop_duplicates(subset='_key').set_index('_key')['вид_дохода_расхода']
df_9101['вид_дохода_расхода'] = df_9101['_key'].map(mapping).astype('string')
df_9102['вид_дохода_расхода'] = df_9102['_key'].map(mapping).astype('string')

# Убираем временный ключ
df_9101.drop(columns='_key', inplace=True)
df_9102.drop(columns='_key', inplace=True)
reference_df.drop(columns='_key', inplace=True)

# Заполняем отсутствующие значения
df_9101['вид_дохода_расхода'] = df_9101['вид_дохода_расхода'].fillna("не_указано")
df_9101 = df_9101.dropna(axis='columns', how='all')

df_9102['вид_дохода_расхода'] = df_9102['вид_дохода_расхода'].fillna("не_указано")
df_9102 = df_9102.dropna(axis='columns', how='all')

In [371]:
# 91.01 отдельно

# -------------------Добавим доп признак (столбец "объект для изм ппа") для Изменения ППА - столбец с ППА, чтобы найти по нему КА из Справочника (лист "ППА") -----------------№
mask_ppa = df_9101['Корр.счет'].astype(str).str.startswith(PPA_ACCOUNTS, na=False)
df_9101['объект для изм ппа'] = df_9101['Субконто Дт_1'].where(mask_ppa, 'не_указано').astype('string')

# 1. Маска по типу дохода (единое условие для обоих случаев)
mask_income = df_9101['вид_дохода_расхода'] == "Доходы от выбытия прав пользования активами, изменения условий договоров аренды"

# 2. Маски по корр.счету
mask_01_09 = df_9101['Корр.счет'].str.startswith("01.09", na=False)
mask_02_01_or_01_01 = df_9101['Корр.счет'].str.startswith(("02.01", "01.01"), na=False)

# 3. Маппинги из справочника ППА (с защитой от дубликатов)
mapping_ppa = (
    reference_ppa_df
    .drop_duplicates(subset='ос_ппа')
    .set_index('ос_ппа')['контрагент']
)
mapping_transfer = (
    reference_ppa_df
    .drop_duplicates(subset='ос_после_перехода_в_собственность')
    .set_index('ос_после_перехода_в_собственность')['контрагент']
)

# 4. Условие 1: 01.09 → поиск по "ос_ппа"
mask_1 = mask_income & mask_01_09
mapped_1 = df_9101['объект для изм ппа'].map(mapping_ppa)

count_1 = (mask_1 & mapped_1.notna()).sum()
df_9101['контрагент'] = np.where(
    mask_1 & mapped_1.notna(),   # заменить только там, где условие И найдено значение
    mapped_1,                     # новое значение
    df_9101['контрагент']         # иначе — оставить текущее
)

# 5. Условие 2: 02.01 или 01.01 → поиск по "ос_после_перехода_в_собственность"
mask_2 = mask_income & mask_02_01_or_01_01
mapped_2 = df_9101['объект для изм ппа'].map(mapping_transfer)

count_2 = (mask_2 & mapped_2.notna()).sum()
df_9101['контрагент'] = np.where(
    mask_2 & mapped_2.notna(),
    mapped_2,
    df_9101['контрагент']
)

# 6. Явное приведение к string (np.where часто возвращает object)
df_9101['контрагент'] = df_9101['контрагент'].astype('string')
# -------------------КОНЕЦ Добавим доп признак (столбец "объект для изм ппа") для Изменения ППА-----------------------


# -------------------# Вид связи -----------------------
def calculate_connection_type(df_result: pd.DataFrame) -> pd.Series:
        """Рассчитывает вид_связи на основе группа_ка и сегмент_ка."""
        conditions = [
            df_result['группа_ка'] == '3 лица',
            df_result['группа_ка'] == 'Прочие ГАП',
            (df_result['группа_ка'] == 'ГСК') & (df_result['сегмент_ка'] == df_result['сегмент']),
            (df_result['группа_ка'] == 'ГСК') & (df_result['сегмент_ка'] != df_result['сегмент']),
        ]
        choices = [
            '3 лица',
            'Прочие ГАП',
            'ГСК внутрисегмент.',
            'ГСК межсегмент.',
        ]
        # ★ STRING вместо category
        result = np.select(conditions, choices, default='не_указано')
        return pd.Series(result, index=df_result.index, dtype='string')

# группа_ка и сегмент_ка (из group_companies_df по контрагенту)
group_unique = group_companies_df.drop_duplicates(subset='ВариантыНазвания')
        
mapping_group = group_unique.set_index('ВариантыНазвания')['ВидСвязиКА'].astype('string')
mapping_segment_ka = group_unique.set_index('ВариантыНазвания')['сегмент'].astype('string')
        
df_9101['группа_ка'] = df_9101['контрагент'].map(mapping_group).fillna('3 лица').astype('string')
df_9101['сегмент_ка'] = df_9101['контрагент'].map(mapping_segment_ka).fillna('3 лица').astype('string')

segment_company = companies_df.loc[companies_df['сокращенное_наименование_компании'] == name_company, 'сегмент'].values[0]

df_9101['сегмент'] = segment_company

df_9101['вид_связи'] = calculate_connection_type(df_9101)

df_9101.head()

,Имя_файла,Дата,Документ,Корр.счет,счет,"оборот, тыс.ед.",Содержание_1,Содержание_2,Субконто Дт_1,Субконто Дт_2,доход_расход,Субконто Дт_3,контрагент,вид_дохода_расхода,объект для изм ппа,группа_ка,сегмент_ка,сегмент,вид_связи
112255,РЗК_отчпровод_91.01_2025_.txt,2025-01-01 23:59:59,Корректировка долга ТЗ000000047 от 01.01.2025 ...,60.01,91.01,-0.65,Оплата,<NA>,РТ-РЕГИСТРАТОР АО,Счет на оплату по прейскуранту,Доходы и расходы по результатам инвентаризации...,<NA>,РТ-РЕГИСТРАТОР АО,Доходы от инвентаризации,не_указано,3 лица,3 лица,Растениеводство,3 лица
112256,РЗК_отчпровод_91.01_2025_.txt,2025-01-01 23:59:59,Корректировка долга ТЗ000000062 от 01.01.2025 ...,60.02,91.01,-0.01,Оплата (аванс),<NA>,ЦОК АПК ФГБУ,Договор оказания услуг РЦ-К № 130 от 05.02.2020г.,Доходы и расходы по результатам инвентаризации СХ,<NA>,ЦОК АПК ФГБУ,Доходы от инвентаризации,не_указано,3 лица,3 лица,Растениеводство,3 лица
112257,РЗК_отчпровод_91.01_2025_.txt,2025-01-01 23:59:59,Оприходование товаров ТЦ000000010 от 01.01.202...,43,91.01,-4.54,Оприходование излишков,Количество,Пшеница озимая Урожай 2024 4 класс,Склад ГП ф. Тацинский,Доходы и расходы по результатам инвентаризации СХ,<NA>,не_указано,Доходы от инвентаризации,не_указано,3 лица,3 лица,Растениеводство,3 лица
112258,РЗК_отчпровод_91.01_2025_.txt,2025-01-01 23:59:59,Оприходование товаров ТЦ000000013 от 01.01.202...,43,91.01,-9.23,Оприходование излишков,Количество,Пшеница озимая Урожай 2024 4 класс,Склад ГП ф. Тацинский,Доходы и расходы по результатам инвентаризации СХ,<NA>,не_указано,Доходы от инвентаризации,не_указано,3 лица,3 лица,Растениеводство,3 лица
112259,РЗК_отчпровод_91.01_2025_.txt,2025-01-01 23:59:59,Оприходование товаров ТЗ000000003 от 01.01.202...,43,91.01,-5.28,Оприходование излишков,Количество,Пшеница озимая Урожай 2024 4 класс,"ПАО ""Миллеровский элеватор""",Доходы и расходы по результатам инвентаризации СХ,<NA>,не_указано,Доходы от инвентаризации,не_указано,3 лица,3 лица,Растениеводство,3 лица

In [372]:
# =========================================================================
# ЗАДАЧА 1: Уменьшение выручки от реализации активов на сумму НДС
# =========================================================================

# 1. Фильтруем только строки с продажей активов
ASSET_SALE_TYPES = ['Продажа прочего имущества', 'Продажа основных средств']

df_9101_assets = df_9101[
    df_9101['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
].copy()

df_9102_assets = df_9102[
    df_9102['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
].copy()

# logger.debug(
#     f"Продажа активов: {len(df_9101_assets)} строк доходов, "
#     f"{len(df_9102_assets)} строк расходов"
# )

print(
    f"Продажа активов: {len(df_9101_assets)} строк доходов, "
    f"{len(df_9102_assets)} строк расходов"
)

# 2. Выделяем НДС из df_9102 (Корр.счет начинается с "68")
mask_vat = df_9102_assets['Корр.счет'].astype(str).str.startswith('68', na=False)
df_9102_vat = df_9102_assets[mask_vat].copy()

# Суммируем НДС по Документу (на случай нескольких записей по 68 счету)
vat_by_doc = (
    df_9102_vat
    .groupby('Документ', as_index=False)['оборот, тыс.ед.']
    .sum()
    .rename(columns={'оборот, тыс.ед.': 'ндс_тыс_ед'})
)

# logger.debug(
#     f"Найдено {len(vat_by_doc)} документов с НДС, "
#     f"сумма НДС={vat_by_doc['ндс_тыс_ед'].sum():,.2f} тыс.ед."
# )

print(
    f"Найдено {len(vat_by_doc)} документов с НДС, "
    f"сумма НДС={vat_by_doc['ндс_тыс_ед'].sum():,.2f} тыс.ед."
)

# 3. Объединяем выручку с НДС через merge
df_9101_assets = df_9101_assets.merge(
    vat_by_doc, 
    on='Документ', 
    how='left'
)

# Заполняем NaN нулями для документов без НДС
df_9101_assets['ндс_тыс_ед'] = df_9101_assets['ндс_тыс_ед'].fillna(0)

# 4. Уменьшаем выручку на НДС
df_9101_assets['оборот, тыс.ед.'] = (
    df_9101_assets['оборот, тыс.ед.'] - df_9101_assets['ндс_тыс_ед']
)

# Логируем статистику
adjusted_count = (df_9101_assets['ндс_тыс_ед'] > 0).sum()
total_vat = df_9101_assets['ндс_тыс_ед'].sum()
# logger.debug(
#     f"Скорректировано {adjusted_count} строк выручки, "
#     f"сумма вычтенного НДС={total_vat:,.2f} тыс.ед."
# )
print(
    f"Скорректировано {adjusted_count} строк выручки, "
    f"сумма вычтенного НДС={total_vat:,.2f} тыс.ед."
)

# 5. Обновляем df_9101: заменяем строки с продажей активов на скорректированные
#    (остальные строки остаются без изменений)
mask_assets_in_9101 = df_9101['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
df_9101_result = pd.concat([
    df_9101[~mask_assets_in_9101],  # Все кроме продажи активов
    df_9101_assets.drop(columns=['ндс_тыс_ед'])  # Скорректированные (без служебного столбца)
], ignore_index=True)

# 6. Удаляем строки с НДС из df_9102
df_9102_result = df_9102_assets[~mask_vat].copy()

# Объединяем с остальными строками df_9102 (которые не относятся к продаже активов)
mask_assets_in_9102 = df_9102['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
df_9102_result = pd.concat([
    df_9102[~mask_assets_in_9102],  # Все кроме продажи активов
    df_9102_result  # Продажа активов без НДС
], ignore_index=True)

# 7. Явное приведение типов к string (на случай, если concat сломал)
text_cols = ['Документ', 'Корр.счет', 'счет', 'доход_расход', 
             'вид_дохода_расхода', 'контрагент']
for col in text_cols:
    if col in df_9101_result.columns:
        df_9101_result[col] = df_9101_result[col].astype('string')
    if col in df_9102_result.columns:
        df_9102_result[col] = df_9102_result[col].astype('string')

# logger.info(
#     f"✓ Обработка НДС завершена: df_9101 ({len(df_9101_result)} строк), "
#     f"df_9102 ({len(df_9102_result)} строк)"
# )
print(
    f"✓ Обработка НДС завершена: df_9101 ({len(df_9101_result)} строк), "
    f"df_9102 ({len(df_9102_result)} строк)"
)

Продажа активов: 253 строк доходов, 446 строк расходов
Найдено 206 документов с НДС, сумма НДС=28,661.18 тыс.ед.
Скорректировано 206 строк выручки, сумма вычтенного НДС=28,661.18 тыс.ед.
✓ Обработка НДС завершена: df_9101 (10179 строк), df_9102 (68753 строк)

In [373]:
# =========================================================================
# ЗАДАЧА 2: Подтягивание контрагентов из df_9101 в df_9102
# (только для строк, относящихся к продаже активов)
# =========================================================================

# 1. Признаки продажи активов
ASSET_SALE_TYPES = ['Продажа прочего имущества', 'Продажа основных средств']

# 2. Маски для фильтрации только строк с продажей активов
mask_assets_9101 = df_9101_result['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
mask_assets_9102 = df_9102_result['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)

# 3. Создаём маппинг Документ → контрагент ТОЛЬКО из строк продажи активов в df_9101
contractor_mapping = (
    df_9101_result.loc[mask_assets_9101, ['Документ', 'контрагент']]
    .drop_duplicates(subset='Документ', keep='first')
    .set_index('Документ')['контрагент']
)
connection_mapping = (
    df_9101_result.loc[mask_assets_9101, ['Документ', 'вид_связи']]
    .drop_duplicates(subset='Документ', keep='first')
    .set_index('Документ')['вид_связи']
)
# 4. ★ Проверка: нет ли документов с разными покупателями в df_9101 (аномалия)
docs_with_multiple_buyers = (
    df_9101_result.loc[mask_assets_9101]
    .groupby('Документ')['контрагент']
    .nunique()
)
problem_docs = docs_with_multiple_buyers[docs_with_multiple_buyers > 1]

if len(problem_docs) > 0:
    # logger.warning(
    #     f"⚠️ Обнаружено {len(problem_docs)} документов с разными покупателями "
    #     f"в df_9101 (продажа активов): {list(problem_docs.index[:5])}..."
    # )
    print(
        f"⚠️ Обнаружено {len(problem_docs)} документов с разными покупателями "
        f"в df_9101 (продажа активов): {list(problem_docs.index[:5])}..."
    )

# 5. Подтягиваем контрагентов только для строк продажи активов в df_9102
mask_unspecified = (
    mask_assets_9102 &
    (df_9102_result['контрагент'] == 'не_указано')
)
mapped_contractors = df_9102_result.loc[mask_unspecified, 'Документ'].map(contractor_mapping)

# 6. Заменяем только там, где удалось подтянуть значение
df_9102_result.loc[mask_unspecified, 'контрагент'] = np.where(
    mapped_contractors.notna(),
    mapped_contractors,
    'не_указано'
)
# ★ 4. Подтягиваем вид_связи (НОВОЕ!)
mapped_connections = df_9102_result.loc[mask_unspecified, 'Документ'].map(connection_mapping)

# Если столбца 'вид_связи' ещё нет в df_9102 — создаём с NaN
if 'вид_связи' not in df_9102_result.columns:
    df_9102_result['вид_связи'] = pd.NA

df_9102_result.loc[mask_unspecified, 'вид_связи'] = np.where(
    mapped_connections.notna(),
    mapped_connections,
    df_9102_result.loc[mask_unspecified, 'вид_связи']  # оставить как было
)

# 5. Явное приведение к string
df_9102_result['контрагент'] = df_9102_result['контрагент'].astype('string')
df_9102_result['вид_связи'] = df_9102_result['вид_связи'].astype('string')

# 6. Статистика
replaced_contractors = mapped_contractors.notna().sum()
replaced_connections = mapped_connections.notna().sum()

# logger.debug(
#     f"Подтягивание из df_9101: "
#     f"{replaced_contractors} контрагентов, "
#     f"{replaced_connections} вид_связи"
# )
print(
    f"Подтягивание из df_9101: "
    f"{replaced_contractors} контрагентов, "
    f"{replaced_connections} вид_связи"
)


# 7. Явное приведение к string (np.where часто возвращает object)
df_9102_result['контрагент'] = df_9102_result['контрагент'].astype('string')

# 8. Статистика
replaced_count = mapped_contractors.notna().sum()
not_found_count = mapped_contractors.isna().sum()
total_assets = mask_assets_9102.sum()

# logger.debug(
#     f"Подтягивание контрагентов для продажи активов: "
#     f"обработано {total_assets} строк расходов, "
#     f"{replaced_count} обновлено, "
#     f"{not_found_count} документов не найдено в df_9101"
# )
print(
    f"Подтягивание контрагентов для продажи активов: "
    f"обработано {total_assets} строк расходов, "
    f"{replaced_count} обновлено, "
    f"{not_found_count} документов не найдено в df_9101"
)
df_9102_result.head()

Подтягивание из df_9101: 202 контрагентов, 202 вид_связи
Подтягивание контрагентов для продажи активов: обработано 240 строк расходов, 202 обновлено, 38 документов не найдено в df_9101

,Имя_файла,Дата,Документ,счет,Корр.счет,"оборот, тыс.ед.",Содержание_1,Содержание_2,доход_расход,Субконто Кт_1,Субконто Кт_2,Субконто Кт_3,контрагент,вид_дохода_расхода,вид_связи
0,РЗК_отчпровод_91.02_2025_.txt,2025-01-01,Авансовый отчет ВГ000000006 от 01.01.2025 0:00:00,91.02.1,71.01,39.71,Проведение новогоднего мероприятия по отчет бн...,<NA>,Доходы (расходы) НЕ НУ,Камбулова Ирина Анатольевна,<NA>,<NA>,не_указано,Прочие,<NA>
1,РЗК_отчпровод_91.02_2025_.txt,2025-01-01,Операция (бухгалтерский и налоговый учет) 0000...,91.02.1,10.11,-0.23,<NA>,Количество,Доходы и расходы по результатам инвентаризации...,Перчатки х/б с 2-м латексным покрыт.,<NA>,<NA>,не_указано,Расходы по инвентаризации,<NA>
2,РЗК_отчпровод_91.02_2025_.txt,2025-01-01,Операция (бухгалтерский и налоговый учет) 0000...,91.02.1,10.11,5.28,<NA>,Количество,Доходы и расходы по результатам инвентаризации...,Перчатки латексные,<NA>,<NA>,не_указано,Расходы по инвентаризации,<NA>
3,РЗК_отчпровод_91.02_2025_.txt,2025-01-01,Операция (бухгалтерский и налоговый учет) 0000...,91.02.1,10.05,0.00,<NA>,Количество,Доходы и расходы по результатам инвентаризации...,Датчик контроля угла наклона ДУ-Р2 (беспроводной),<NA>,<NA>,не_указано,Расходы по инвентаризации,<NA>
4,РЗК_отчпровод_91.02_2025_.txt,2025-01-01,Операция (бухгалтерский и налоговый учет) 0000...,91.02.1,10.05,-0.00,<NA>,Количество,Доходы и расходы по результатам инвентаризации...,"Палец 26950030032/ 3507-01-80.00.002 (D=60мм, ...",<NA>,<NA>,не_указано,Расходы по инвентаризации,<NA>

In [374]:
# =========================================================================
# РАСПРЕДЕЛЕНИЕ "ОСИРОТЕВШИХ" РАСХОДОВ (продажа активов на 91 счете) ПРОПОРЦИОНАЛЬНО ВЫРУЧКЕ
# =========================================================================

# 1. Константы
ASSET_SALE_TYPES = ['Продажа прочего имущества', 'Продажа основных средств']

# 2. Фильтруем только продажу активов
mask_9101_assets = df_9101_result['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
mask_9102_assets = df_9102_result['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)

df_9101_assets = df_9101_result[mask_9101_assets].copy()
df_9102_assets = df_9102_result[mask_9102_assets].copy()

# 3. Определяем документы-сироты (есть в df_9102, но нет в df_9101)
docs_in_9101 = set(df_9101_assets['Документ'].unique())
docs_in_9102 = set(df_9102_assets['Документ'].unique())
orphan_docs = docs_in_9102 - docs_in_9101

print(
    f"Продажа активов: {len(docs_in_9101)} документов в доходах, "
    f"{len(docs_in_9102)} документов в расходах, "
    f"{len(orphan_docs)} документов-сирот"
)
# logger.debug(
#     f"Продажа активов: {len(docs_in_9101)} документов в доходах, "
#     f"{len(docs_in_9102)} документов в расходах, "
#     f"{len(orphan_docs)} документов-сирот"
# )

# Разделяем df_9102 на привязанные и осиротевшие
mask_orphan = df_9102_assets['Документ'].isin(orphan_docs)
df_9102_attached = df_9102_assets[~mask_orphan].copy()
df_9102_orphan = df_9102_assets[mask_orphan].copy()

# =========================================================================
# РАСПРЕДЕЛЕНИЕ ОСИРОТЕВШИХ ДОКУМЕНТОВ
# =========================================================================

if not df_9102_orphan.empty:
    # 4. ★ Создаём маппинг контрагент → вид_связи из df_9101
    #    Берём первое вхождение на случай, если один контрагент в нескольких документах
    contractor_to_connection = (
        df_9101_assets[['контрагент', 'вид_связи']]
        .drop_duplicates(subset='контрагент', keep='first')
        .set_index('контрагент')['вид_связи']
    )
    
    # 5. ★ Расчёт долей выручки каждого контрагента в рамках вид_дохода_расхода
    #    Используем transform для сохранения индекса
    revenue_by_type = df_9101_assets.groupby('вид_дохода_расхода')['оборот, тыс.ед.'].transform('sum')
    df_9101_assets['доля_контрагента'] = df_9101_assets['оборот, тыс.ед.'] / revenue_by_type
    
    # Агрегируем: на каждого контрагента в рамках вид_дохода_расхода — его суммарная доля
    # (контрагент может быть в нескольких документах продажи)
    contractor_share = (
        df_9101_assets.groupby(['вид_дохода_расхода', 'контрагент'], as_index=False)
        ['доля_контрагента'].sum()
    )
    
    # удаляем 'контрагент' перед merge, чтобы не было суффиксов _x/_y
    df_9102_orphan = df_9102_orphan.drop(columns=['контрагент'], errors='ignore')
    # 6. Cross-join: каждый документ-сирота × каждый контрагент (в рамках вид_дохода_расхода)
    #    Добавляем ключ для join по вид_дохода_расхода
    df_9102_orphan_dist = df_9102_orphan.merge(
        contractor_share,
        on='вид_дохода_расхода',
        how='inner'  # только те вид_дохода_расхода, по которым есть выручка
    )
    
    # 7. Распределяем оборот пропорционально долям
    df_9102_orphan_dist['оборот_распределенный'] = (
        df_9102_orphan_dist['оборот, тыс.ед.'] * df_9102_orphan_dist['доля_контрагента']
    )

    # 8. Подтягиваем вид_связи из маппинга
    df_9102_orphan_dist['вид_связи'] = (
        df_9102_orphan_dist['контрагент'].map(contractor_to_connection).astype('string')
    )
    
    # 9. Финальная очистка
    df_9102_orphan_dist = df_9102_orphan_dist.drop(
        columns=['оборот, тыс.ед.', 'доля_контрагента']
    )
    df_9102_orphan_dist = df_9102_orphan_dist.rename(
        columns={'оборот_распределенный': 'оборот, тыс.ед.'}
    )
    
    # Обновляем контрагент (в df_9102_orphan он был 'не_указано', теперь — конкретный)
    # Убираем служебные столбцы и оставляем только нужные
    df_9102_orphan_dist = df_9102_orphan_dist.drop(
        columns=['контрагент_x'], errors='ignore'  # если был дубль после merge
    )
    
    # logger.debug(
    #     f"Распределено {len(df_9102_orphan)} осиротевших строк "
    #     f"на {len(df_9102_orphan_dist)} строк по {contractor_share['контрагент'].nunique()} контрагентам"
    # )
    print(
        f"Распределено {len(df_9102_orphan)} осиротевших строк "
        f"на {len(df_9102_orphan_dist)} строк по {contractor_share['контрагент'].nunique()} контрагентам"
    )
else:
    df_9102_orphan_dist = pd.DataFrame()
    # logger.debug("Осиротевших документов не найдено")
    print("Осиротевших документов не найдено")

# =========================================================================
# ОБЪЕДИНЕНИЕ РЕЗУЛЬТАТОВ
# =========================================================================

# 10. Собираем обратно: привязанные + распределённые
df_9102_assets_updated = pd.concat(
    [df_9102_attached, df_9102_orphan_dist],
    ignore_index=True
)

# 11. ★ Проверка сходимости: сумма по осиротевшим документам не должна измениться
if not df_9102_orphan.empty and not df_9102_orphan_dist.empty:
    sum_before = df_9102_orphan['оборот, тыс.ед.'].sum()
    sum_after = df_9102_orphan_dist['оборот, тыс.ед.'].sum()
    difference = abs(sum_before - sum_after)
    
    if difference > 0.01:  # допуск на округление
        # logger.warning(
        #     f"⚠️ Расхождение при распределении: было {sum_before:,.2f}, "
        #     f"стало {sum_after:,.2f}, разница {difference:,.2f} тыс.ед."
        # )
        print(
            f"⚠️ Расхождение при распределении: было {sum_before:,.2f}, "
            f"стало {sum_after:,.2f}, разница {difference:,.2f} тыс.ед."
        )
    else:
        # logger.debug(f"✓ Сумма осиротевших документов сохранена: {sum_after:,.2f}")
        print(f"✓ Сумма осиротевших документов сохранена: {sum_after:,.2f}")

# 12. Явное приведение текстовых столбцов к string (на случай object после concat)
text_cols = ['Документ', 'Корр.счет', 'счет', 'доход_расход', 
             'вид_дохода_расхода', 'контрагент', 'вид_связи']
for col in text_cols:
    if col in df_9102_assets_updated.columns:
        df_9102_assets_updated[col] = df_9102_assets_updated[col].astype('string')

# 13. ★ Обновляем основной df_9102: заменяем строки продажи активов на обновлённые
#     (остальные строки остаются без изменений)
mask_assets_in_main = df_9102_result['вид_дохода_расхода'].isin(ASSET_SALE_TYPES)
df_9102_result = pd.concat([
    df_9102_result[~mask_assets_in_main],        # Все кроме продажи активов
    df_9102_assets_updated                 # Обновлённые строки
], ignore_index=True)

# logger.info(
#     f"✓ Распределение завершено: df_9102 = {len(df_9102)} строк "
#     f"(в т.ч. {len(df_9102_assets_updated)} по продаже активов)"
# )
print(
    f"✓ Распределение завершено: df_9102 = {len(df_9102)} строк "
    f"(в т.ч. {len(df_9102_assets_updated)} по продаже активов)"
)

Продажа активов: 253 документов в доходах, 192 документов в расходах, 11 документов-сирот
Распределено 38 осиротевших строк на 682 строк по 66 контрагентам
✓ Сумма осиротевших документов сохранена: 187.64
✓ Распределение завершено: df_9102 = 68959 строк (в т.ч. 884 по продаже активов)

In [375]:
mask_a = df_9101_result['Документ']=="Передача ОС ГА000000001 от 11.02.2025 9:02:17"
df_9101_result[mask_a]

,Имя_файла,Дата,Документ,Корр.счет,счет,"оборот, тыс.ед.",Содержание_1,Содержание_2,Субконто Дт_1,Субконто Дт_2,доход_расход,Субконто Дт_3,контрагент,вид_дохода_расхода,объект для изм ппа,группа_ка,сегмент_ка,сегмент,вид_связи
9927,РЗК_отчпровод_91.01_2025_.txt,2025-02-11 09:02:17,Передача ОС ГА000000001 от 11.02.2025 9:02:17,62.01,91.01,-904.17,<NA>,<NA>,Смыков Александр Сергеевич ИП,Договор купли-продажи №507/24Р от 08 апреля 20...,Доходы и расходы от реализации основных средст...,<NA>,Смыков Александр Сергеевич ИП,Продажа основных средств,не_указано,3 лица,3 лица,Растениеводство,3 лица

In [376]:
mask_b = df_9102_result['Документ']=="Передача ОС ГА000000001 от 11.02.2025 9:02:17"
df_9102_result[mask_b]

,Имя_файла,Дата,Документ,счет,Корр.счет,"оборот, тыс.ед.",Содержание_1,Содержание_2,доход_расход,Субконто Кт_1,Субконто Кт_2,Субконто Кт_3,контрагент,вид_дохода_расхода,вид_связи
68513,РЗК_отчпровод_91.02_2025_.txt,2025-02-11 09:02:17,Передача ОС ГА000000001 от 11.02.2025 9:02:17,91.02.1,01.09,282.22,Передача ОС,<NA>,Доходы и расходы от реализации основных средст...,"Опрыскиватель самоходный ОС 0100 ROSA-01, гос....",<NA>,<NA>,Смыков Александр Сергеевич ИП,Продажа основных средств,3 лица

In [377]:
# --------------------Обслуживание кредитных линий для 91.01-------------------------------
# Вытащить из субконто 97 счета РБП, это рбп по кредитным линиям. По этим РБП достать из справочника "КредитОбслуж" КА -> Сегмент КА -> Вид связи
# Обслужиание кредитных линий - это списание в расходы капитализации услуг УК, банков и страховых с 97 счета
# Отфильтруем данные по вид_дохода_расхода и корр счету
mask = ((df_9101_result['вид_дохода_расхода'] == 'Кредитное обслуживание и расходы по открытию кредитных линий')
        & (df_9101_result['Корр.счет'].str.startswith('97')))

# субконто у корр.счета 97 это рбп по кредитным линиям. По этому рбп через справочник мы вытащим контрагента
# создадим столбец 'рбп_кредитные_линии'
df_9101_result['рбп_кредитные_линии'] = df_9101_result.loc[:, 'Субконто Дт_1'].where(mask, 'не_указано')

# справочник по рбп кредитные линии отфильтрованный по компании:
reference_rbp_credit = reference_rbp_credit.loc[reference_rbp_credit['компания'] == name_company]

# Маппинг из справочника КредитОбслуж (с защитой от дубликатов)
mapping_rbp_credit = (
    reference_rbp_credit
    .drop_duplicates(subset='рбп_кредитные_линии')
    .set_index('рбп_кредитные_линии')['контрагент'])

df_9101_result['контрагент'] = df_9101_result['рбп_кредитные_линии'].map(mapping_rbp_credit).fillna(df_9101_result['контрагент']).astype('string')
df_9101_result['вид_связи'] = calculate_connection_type(df_9101_result)
df_9101_result[df_9101_result['вид_дохода_расхода'] == 'Кредитное обслуживание и расходы по открытию кредитных линий']

,Имя_файла,Дата,Документ,Корр.счет,счет,"оборот, тыс.ед.",Содержание_1,Содержание_2,Субконто Дт_1,Субконто Дт_2,доход_расход,Субконто Дт_3,контрагент,вид_дохода_расхода,объект для изм ппа,группа_ка,сегмент_ка,сегмент,вид_связи,рбп_кредитные_линии
1341,РЗК_отчпровод_91.01_2025_.txt,2025-03-01 00:00:00,Корректировка записей регистров 00000000860 от...,97.21,91.01,-30.23,Договор страх-я спецтехники и оборудования № Р...,<NA>,Дог.страх.№РД-56-00-0033007 от 23.01.2024 по д...,<NA>,Кредитное обслуживание и расходы по открытию к...,<NA>,РСХБ-СТРАХОВАНИЕ СК АО,Кредитное обслуживание и расходы по открытию к...,не_указано,3 лица,3 лица,Растениеводство,3 лица,Дог.страх.№РД-56-00-0033007 от 23.01.2024 по д...
4303,РЗК_отчпровод_91.01_2025_.txt,2025-05-16 16:17:25,Корректировка долга ТЗ000000182 от 16.05.2025 ...,76.05.6,91.01,-0.00,Оплата,<NA>,РСХБ-СТРАХОВАНИЕ СК АО,Договор страхования имущества №СТ-56-23-001648...,Кредитное обслуживание и расходы по открытию к...,<NA>,РСХБ-СТРАХОВАНИЕ СК АО,Кредитное обслуживание и расходы по открытию к...,не_указано,3 лица,3 лица,Растениеводство,3 лица,не_указано

In [378]:
df_9102_result[df_9102_result['вид_дохода_расхода'] == 'Кредитное обслуживание и расходы по открытию кредитных линий'].head()

,Имя_файла,Дата,Документ,счет,Корр.счет,"оборот, тыс.ед.",Содержание_1,Содержание_2,доход_расход,Субконто Кт_1,Субконто Кт_2,Субконто Кт_3,контрагент,вид_дохода_расхода,вид_связи
4909,РЗК_отчпровод_91.02_2025_.txt,2025-01-31 23:59:59,Расходы на страхование 00000000001 от 31.01.20...,91.02.1,97.21,79.92,Списание РБП,<NA>,Кредитное обслуживание и расходы по открытию к...,ДОГОВОР/ПОЛИС СТРАХОВАНИЯ СПЕЦТЕХНИКИ № 80712/...,<NA>,<NA>,не_указано,Кредитное обслуживание и расходы по открытию к...,<NA>
4923,РЗК_отчпровод_91.02_2025_.txt,2025-01-31 23:59:59,Списание расходов будущих периодов 00000000002...,91.02.1,97.21,7.33,Списание РБП,<NA>,Кредитное обслуживание и расходы по открытию к...,Дополнительные расходы по КД №150700/0018 от 2...,<NA>,<NA>,не_указано,Кредитное обслуживание и расходы по открытию к...,<NA>
4924,РЗК_отчпровод_91.02_2025_.txt,2025-01-31 23:59:59,Списание расходов будущих периодов 00000000002...,91.02.1,97.21,351.85,Списание РБП,<NA>,Кредитное обслуживание и расходы по открытию к...,ГАП Дополнительные расходы по КД №0255/23 от 1...,<NA>,<NA>,не_указано,Кредитное обслуживание и расходы по открытию к...,<NA>
4925,РЗК_отчпровод_91.02_2025_.txt,2025-01-31 23:59:59,Списание расходов будущих периодов 00000000002...,91.02.1,97.21,273.46,Списание РБП,<NA>,Кредитное обслуживание и расходы по открытию к...,Дополнительные расходы по КД № 520B00GJG от 23...,<NA>,<NA>,не_указано,Кредитное обслуживание и расходы по открытию к...,<NA>
4926,РЗК_отчпровод_91.02_2025_.txt,2025-01-31 23:59:59,Списание расходов будущих периодов 00000000002...,91.02.1,97.21,7.35,Списание РБП,<NA>,Кредитное обслуживание и расходы по открытию к...,Дополнительные расходы по КД № 520B00J9R от 23...,<NA>,<NA>,не_указано,Кредитное обслуживание и расходы по открытию к...,<NA>

In [379]:
# --------------------Обслуживание кредитных линий для 91.02-------------------------------
# Вытащить из субконто 97 счета РБП, это рбп по кредитным линиям. По этим РБП достать из справочника "КредитОбслуж" КА -> Сегмент КА -> Вид связи
# Обслужиание кредитных линий - это списание в расходы капитализации услуг УК, банков и страховых с 97 счета
# Отфильтруем данные по вид_дохода_расхода и корр счету
mask = ((df_9102_result['вид_дохода_расхода'] == 'Кредитное обслуживание и расходы по открытию кредитных линий')
        & (df_9102_result['Корр.счет'].str.startswith('97')))

# субконто у корр.счета 97 это рбп по кредитным линиям. По этому рбп через справочник мы вытащим контрагента
# создадим столбец 'рбп_кредитные_линии'
df_9102_result['рбп_кредитные_линии'] = df_9102_result.loc[:, 'Субконто Кт_1'].where(mask, 'не_указано')

# справочник по рбп кредитные линии отфильтрованный по компании:
reference_rbp_credit = reference_rbp_credit.loc[reference_rbp_credit['компания'] == name_company]

# Маппинг из справочника КредитОбслуж (с защитой от дубликатов)
mapping_rbp_credit = (
    reference_rbp_credit
    .drop_duplicates(subset='рбп_кредитные_линии')
    .set_index('рбп_кредитные_линии')['контрагент'])

df_9102_result['контрагент'] = df_9102_result['рбп_кредитные_линии'].map(mapping_rbp_credit).fillna(df_9102_result['контрагент']).astype('string')

mask_credit = df_9102_result['вид_дохода_расхода'] == 'Кредитное обслуживание и расходы по открытию кредитных линий'
mask_missing = df_9102_result['контрагент'] == 'не_указано'

missing_list = (
    df_9102_result
    .loc[mask_credit & mask_missing, 'рбп_кредитные_линии']
    .unique()
    .tolist()
)
if missing_list:
    print(
        f"Обнаружены РБП по кредитным линиям, отсутствующие в справочнике "
        f"КредитОбслуж либо по которым нет контрагента ({len(missing_list)} шт.):\n"
        + "\n".join(f"  - {item}" for item in missing_list)
    )
# if missing_list:
#     logger.warning(
#         f"Обнаружены РБП по кредитным линиям, отсутствующие в справочнике "
#         f"КредитОбслуж либо по которым нет контрагента ({len(missing_list)} шт.):\n"
#         + "\n".join(f"  - {item}" for item in missing_list)
#     )

# группа_ка и сегмент_ка (из group_companies_df по контрагенту)
# group_unique = group_companies_df.drop_duplicates(subset='ВариантыНазвания')
        
# mapping_group = group_unique.set_index('ВариантыНазвания')['ВидСвязиКА'].astype('string')
# mapping_segment_ka = group_unique.set_index('ВариантыНазвания')['сегмент'].astype('string')
        
df_9102_result['группа_ка'] = df_9102_result['контрагент'].map(mapping_group).fillna('3 лица').astype('string')
df_9102_result['сегмент_ка'] = df_9102_result['контрагент'].map(mapping_segment_ka).fillna('3 лица').astype('string')

# segment_company = companies_df.loc[companies_df['сокращенное_наименование_компании'] == name_company, 'сегмент'].values[0]

df_9102_result['сегмент'] = segment_company

df_9102_result['вид_связи'] = calculate_connection_type(df_9102_result)
df_9102_result[df_9102_result['вид_дохода_расхода'] == 'Кредитное обслуживание и расходы по открытию кредитных линий'].head()

Обнаружены РБП по кредитным линиям, отсутствующие в справочнике КредитОбслуж либо по которым нет контрагента (25 шт.):
  - ДОГОВОР/ПОЛИС СТРАХОВАНИЯ СПЕЦТЕХНИКИ № 80712/933/19850/24 от 02.07.2024 г.по дог-у залога №0897007
  - Дополнительные расходы по КД №150700/0018 от 20.02.2015г
  - ГАП Дополнительные расходы по КД №0255/23 от 19.04.2023г
  - Дополнительные расходы по КД № 520B00L8R от 15.08.2023г.
  - ГАП Дополнительные расходы по КД №520B00GJG от 23.06.2023г.
  - ГАП Дополнительные расходы по КД №520B00J9R от 23.06.2023г.
  - ГАП Дополнительные расходы по КД №520B00KDP от 15.08.2023г.
  - ГАП Дополнительные расходы по КД №0897/23 от 27.10.2023г
  - ГАП Дополнительные расходы по КД №0179/24 от 25.03.2024г.
  - Дополнительные расходы по КД № 520B00TCU от 06.06.2024г.
  - ГАП Дополнительные расходы по КД №520B00TCU от 06.06.2024г.
  - ГАП Дополнительные расходы по КД №0EEC6L от 26.06.2024г.
  - ГАП Дополнительные расходы по КД № 0290/24 от 16.05.2024 г.
  - ГАП Дополнительные расходы по КД №0336/24 от 14.06.2024г.
  - ГАП Дополнительные расходы по КД №0338/24 от 14.06.2024г.
  - ДОГОВОР/ПОЛИС СТРАХОВАНИЯ СПЕЦТЕХНИКИ № 80712/933/19852/24 от 04.07.24 г.по дог залога №0897008/23
  - ГАП Дополнительные расходы по КД №05B90L от 1.03.2022 г
  - Дополнительные расходы по КД № 520B00ZQ6 от 26.07.2024г.
  - Дополнительные расходы по КД № 520B011642LZ от 05.09.2024
  - ГАП Дополнительные расходы по КД №520B00ZQ6 от 26.07.2024г.
  - ГАП Дополнительные расходы по КД №520B011642LZ от 05.09.2024г.
  - ГАП Дополнительные расходы по КД №0FHA4L от 26.06.2024г.
  - Дог. страх. №80712/933/21612/25 от 11.03.2025г по дог. залога №520В00GJG/ДЗ1 от 14.03.2024г
  - Дог. страх. №01/35/169/02662 от 28.06.24г по дог. залога №0290007/24 от 05.12.24г, №0290008/24
  - ДОГ-Р СТРАХОВ-Я СПЕЦТЕХНИКИ №80712/933/19852/24 от 04.07.24 по дог-у залога №0897008/23 от 04.07.24

,Имя_файла,Дата,Документ,счет,Корр.счет,"оборот, тыс.ед.",Содержание_1,Содержание_2,доход_расход,Субконто Кт_1,Субконто Кт_2,Субконто Кт_3,контрагент,вид_дохода_расхода,вид_связи,рбп_кредитные_линии,группа_ка,сегмент_ка,сегмент
4909,РЗК_отчпровод_91.02_2025_.txt,2025-01-31 23:59:59,Расходы на страхование 00000000001 от 31.01.20...,91.02.1,97.21,79.92,Списание РБП,<NA>,Кредитное обслуживание и расходы по открытию к...,ДОГОВОР/ПОЛИС СТРАХОВАНИЯ СПЕЦТЕХНИКИ № 80712/...,<NA>,<NA>,не_указано,Кредитное обслуживание и расходы по открытию к...,3 лица,ДОГОВОР/ПОЛИС СТРАХОВАНИЯ СПЕЦТЕХНИКИ № 80712/...,3 лица,3 лица,Растениеводство
4923,РЗК_отчпровод_91.02_2025_.txt,2025-01-31 23:59:59,Списание расходов будущих периодов 00000000002...,91.02.1,97.21,7.33,Списание РБП,<NA>,Кредитное обслуживание и расходы по открытию к...,Дополнительные расходы по КД №150700/0018 от 2...,<NA>,<NA>,не_указано,Кредитное обслуживание и расходы по открытию к...,3 лица,Дополнительные расходы по КД №150700/0018 от 2...,3 лица,3 лица,Растениеводство
4924,РЗК_отчпровод_91.02_2025_.txt,2025-01-31 23:59:59,Списание расходов будущих периодов 00000000002...,91.02.1,97.21,351.85,Списание РБП,<NA>,Кредитное обслуживание и расходы по открытию к...,ГАП Дополнительные расходы по КД №0255/23 от 1...,<NA>,<NA>,не_указано,Кредитное обслуживание и расходы по открытию к...,3 лица,ГАП Дополнительные расходы по КД №0255/23 от 1...,3 лица,3 лица,Растениеводство
4925,РЗК_отчпровод_91.02_2025_.txt,2025-01-31 23:59:59,Списание расходов будущих периодов 00000000002...,91.02.1,97.21,273.46,Списание РБП,<NA>,Кредитное обслуживание и расходы по открытию к...,Дополнительные расходы по КД № 520B00GJG от 23...,<NA>,<NA>,Сбербанк ПАО,Кредитное обслуживание и расходы по открытию к...,3 лица,Дополнительные расходы по КД № 520B00GJG от 23...,3 лица,3 лица,Растениеводство
4926,РЗК_отчпровод_91.02_2025_.txt,2025-01-31 23:59:59,Списание расходов будущих периодов 00000000002...,91.02.1,97.21,7.35,Списание РБП,<NA>,Кредитное обслуживание и расходы по открытию к...,Дополнительные расходы по КД № 520B00J9R от 23...,<NA>,<NA>,Сбербанк ПАО,Кредитное обслуживание и расходы по открытию к...,3 лица,Дополнительные расходы по КД № 520B00J9R от 23...,3 лица,3 лица,Растениеводство

In [403]:
df_9102_result.loc[df_9102_result['контрагент'] == 'Ресурс Финанс УК ООО'].sample()

,Имя_файла,Дата,Документ,счет,Корр.счет,"оборот, тыс.ед.",Содержание_1,Содержание_2,доход_расход,Субконто Кт_1,Субконто Кт_2,Субконто Кт_3,контрагент,вид_дохода_расхода,вид_связи,рбп_кредитные_линии,группа_ка,сегмент_ка,сегмент
25446,РЗК_отчпровод_91.02_2025_.txt,2025-05-31 23:59:59,Списание расходов будущих периодов 00000000005...,91.02.1,97.21,9.92,Списание РБП,<NA>,Кредитное обслуживание и расходы по открытию к...,Дополнительные расходы по КД №210700/0039 от 2...,<NA>,<NA>,Ресурс Финанс УК ООО,Кредитное обслуживание и расходы по открытию к...,ГСК межсегмент.,Дополнительные расходы по КД №210700/0039 от 2...,ГСК,Прочие,Растениеводство

In [382]:
# df_final = pd.concat([df_9101, df_9102], ignore_index=True)
# df_final